# -*- coding: utf-8 -*-
"""Ablantion_studies.ipynb

Automatically generated by Colab.

# 1. Installing libraries

Installing latex
"""

!apt-get -qq install -y fonts-freefont-ttf texlive-latex-extra texlive-fonts-recommended dvipng cm-super

!apt-get -qq install -y fonts-freefont-ttf > /dev/null 2>&1

"""Installing uv python package"""

!pip install uv

!uv pip install gdown torch pytorch_lightning xgboost optuna lightgbm catboost tqdm optuna scienceplots

"""# 2. Importing libraries and taking configurations"""

import copy
import json
import os
import warnings
from itertools import combinations

import numpy as np
import pandas as pd
from scipy.stats import ks_2samp
import matplotlib.pyplot as plt
import scienceplots
from sklearn.ensemble import AdaBoostRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import KFold, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeRegressor, plot_tree
import catboost as cb
import lightgbm as lgb
import xgboost as xgb

import matplotlib
import matplotlib.font_manager
matplotlib.font_manager._load_fontmanager(try_read_cache=False)

import torch
import pytorch_lightning as pl

from optuna.visualization.matplotlib import (
    plot_optimization_history, plot_param_importances,
    plot_parallel_coordinate, plot_contour,
)

import gdown
import joblib
import optuna
from tqdm import tqdm

plt.style.use(['science'])

optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings('ignore')
np.random.seed(42); torch.manual_seed(42)
pl.seed_everything(42, workers=True)

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

SEEDS = [42, 137, 256, 1024, 7, 314, 999, 2048, 55, 8080,
         12345, 67890, 101, 404, 808, 1337, 2023, 9999, 777, 31415]


print(f"PyTorch {torch.__version__} | PL {pl.__version__} | {DEVICE}")

all_seed_runs = {m: {} for m in ['XGB', 'LightGBM', 'CatBoost', 'AdaBoost', 'RF', 'DecisionTree']}

N_TRIALS = 50

"""#3. Importing wells data"""

dfs_raw = {}
for fn in ['MISSA-KESWAL-01.CSV', 'MISSA-KESWAL-02.CSV', 'MISSA-KESWAL-03.CSV']:
    dfs_raw[fn] = pd.read_csv(f'/content/{fn}')


depth_intervals = {
    'MISSA-KESWAL-01.CSV': (1137, 1802),
    'MISSA-KESWAL-02.CSV': (1115, 1792),
    'MISSA-KESWAL-03.CSV': (1125, 1870),
}

for fn in dfs_raw:
    lo, hi = depth_intervals[fn]
    dfs_raw[fn] = dfs_raw[fn][(dfs_raw[fn]['DEPTH'] >= lo) & (dfs_raw[fn]['DEPTH'] <= hi)]

sorted_files = sorted(dfs_raw.items(), key=lambda x: len(x[1]), reverse=True)
train_df = sorted_files[0][1]
val_df   = sorted_files[1][1]
blind_df = sorted_files[2][1]

print(f"Train: {len(train_df):,} rows ({sorted_files[0][0]})")
print(f"Val:   {len(val_df):,} rows ({sorted_files[1][0]})")
print(f"Blind: {len(blind_df):,} rows ({sorted_files[2][0]})")

"""#4. Processing the data"""

TARGET = 'PPP'
EXCLUDE = {'mw','pp','fp','ves','dphi','nphi','phit','phie','velocity',
           'velocity_nct','ai','cgr','ac','cal','cali','dst','lld','lls','msfl',
           'well_id','wellname','pressure_regime','pressure_ratio','overpressure',
           TARGET,'depth'}

def engineer(df):
    if 'dt' in df.columns and 'dt_nct' in df.columns:
        df['eaton_ratio'] = (df['dt']/df['dt_nct'])**3
    if 'hp' in df.columns and 'tvd' in df.columns:
        tvd_ft = df['tvd']*3.28084
        df['hp_gradient'] = df['hp']/tvd_ft
    if 'ob' in df.columns and 'tvd' in df.columns:
        tvd_ft = df['tvd']*3.28084
        df['ob_gradient'] = df['ob']/tvd_ft
    if 'tvd' in df.columns:
        df['tvd_normalized'] = df['tvd']/df['tvd'].max()
    return df

train_df = engineer(train_df)
val_df   = engineer(val_df)
blind_df = engineer(blind_df)

all_cols = set(train_df.columns) & set(val_df.columns) & set(blind_df.columns)
features = sorted([c for c in all_cols
                   if c not in EXCLUDE
                   and train_df[c].dtype in ['float64','float32','int64']
                   and train_df[c].notna().mean() > 0.65])

print(f"Features ({len(features)}): {features}")
assert TARGET in train_df.columns

for df in [train_df, val_df, blind_df]:
    mask = df[features+[TARGET]].notna().all(axis=1)
    df.drop(df[~mask].index, inplace=True)

N_FEAT = len(features)

combo = pd.concat([train_df, val_df], ignore_index=True)
X_all, y_all = combo[features].values, combo[TARGET].values

scaler = StandardScaler()
scaler.fit(train_df[features].values)
X_all_s = scaler.transform(X_all)
joblib.dump(scaler, 'scaler.pkl')

X_test_s = scaler.transform(blind_df[features].values)
y_test = blind_df[TARGET].values

"""Data for Optuna hyperparameter optimization"""

X_optuna_train = scaler.transform(train_df[features].values)
y_optuna_train = train_df[TARGET].values
X_optuna_val   = scaler.transform(val_df[features].values)
y_optuna_val   = val_df[TARGET].values

if 'well_id' in train_df.columns:
    tw, vw, bw = set(train_df.well_id), set(val_df.well_id), set(blind_df.well_id)
    overlap = (tw & vw) | (tw & bw) | (vw & bw)
    print(f"Well overlap: {'NONE ✓' if not overlap else overlap}")

for f in features[:8]:
    ks, p = ks_2samp(combo[f].dropna(), blind_df[f].dropna())
    tag = "SEV" if ks > .3 else "MOD" if ks > .15 else "ok"
    print(f"  {f:18s} KS={ks:.3f} [{tag}]")

if 'hp' in blind_df.columns:
    for n, df in [('Train', train_df), ('Val', val_df), ('Test', blind_df)]:
        pr = df['ppp'] / df['hp']
        print(f"{n}: U={(pr<.9).mean()*100:.1f}% N={((pr>=.9)&(pr<=1.1)).mean()*100:.1f}% O={(pr>1.1).mean()*100:.1f}%")

"""#5. Loading the data"""

gdown.download_folder(url, quiet=False)

"""Loading all ML models"""

base_path = '/content/optimal_models_parameters/'
model_names = ['XGB', 'LightGBM', 'CatBoost', 'AdaBoost', 'RF', 'DecisionTree']

for model_name in model_names:
    params_file = os.path.join(base_path, f'{model_name}_best_params.json')
    model_file = os.path.join(base_path, f'{model_name}_best.pkl')

    # Load parameters
    with open(params_file, 'r') as f:
        loaded_params = json.load(f)

    # Load model
    loaded_model = joblib.load(model_file)

    # Ensure the seed 42 entry exists before assigning
    if 42 not in all_seed_runs[model_name]:
        all_seed_runs[model_name][42] = {'params': {}, 'metrics': {}}

    # Store the loaded parameters and model in all_seed_runs for seed 42
    all_seed_runs[model_name][42]['params'] = loaded_params
    all_seed_runs[model_name][42]['model'] = loaded_model

    print(f"Loaded {model_name} model and parameters for seed 42.")

print("All optimal tree parameters and models loaded.")

"""# 6. Creating the decision tree meta learner"""

def rename_keys(d, mapping):
    """Rename keys in a dict according to a mapping."""
    out = d.copy()
    for old, new in mapping.items():
        if old in out:
            out[new] = out.pop(old)
    return out

catboost_params = rename_keys(all_seed_runs['CatBoost'][42]['params']['params'], {
    'iters': 'iterations', 'lr': 'learning_rate', 'l2': 'l2_leaf_reg',
    'sub': 'subsample', 'col': 'colsample_bylevel', 'mcs': 'min_child_samples'
})

adaboost_params = rename_keys(all_seed_runs['AdaBoost'][42]['params']['params'], {
    'n_est': 'n_estimators', 'lr': 'learning_rate'
})

rf_params = rename_keys(all_seed_runs['RF'][42]['params']['params'], {
    'n_est': 'n_estimators', 'depth': 'max_depth', 'min_split': 'min_samples_split',
    'min_leaf': 'min_samples_leaf', 'max_feat': 'max_features'
})

dt_params = rename_keys(all_seed_runs['DecisionTree'][42]['params']['params'], {
    'depth': 'max_depth', 'min_split': 'min_samples_split',
    'min_leaf': 'min_samples_leaf', 'max_feat': 'max_features'
})

base_models = [
    xgb.XGBRegressor(**all_seed_runs['XGB'][42]['params']['params'], random_state=42, n_jobs=-1),
    lgb.LGBMRegressor(**all_seed_runs['LightGBM'][42]['params']['params'], random_state=42, n_jobs=-1, verbose=-1),
    cb.CatBoostRegressor(**catboost_params, random_seed=42, verbose=0),
    AdaBoostRegressor(**adaboost_params, random_state=42),
    RandomForestRegressor(**rf_params, random_state=42, n_jobs=-1),
    DecisionTreeRegressor(**dt_params, random_state=42)
]

"""Create arrays to hold the 5 input features (predictions) for the meta-learner"""

X_meta_train = np.zeros((X_all_s.shape[0], 6))
X_meta_test = np.zeros((X_test_s.shape[0], 6))
kf = KFold(n_splits=5, shuffle=True, random_state=42)

for i, model in enumerate(base_models):
    test_preds = np.zeros((X_test_s.shape[0], 5))
    for fold, (tr_idx, val_idx) in enumerate(kf.split(X_all_s)):
        m = copy.deepcopy(model)
        m.fit(X_all_s[tr_idx], y_all[tr_idx])
        X_meta_train[val_idx, i] = m.predict(X_all_s[val_idx])
        test_preds[:, fold] = m.predict(X_test_s)
    X_meta_test[:, i] = test_preds.mean(axis=1)

"""Optimize the Decision Tree Meta-Learner using Optuna"""

def obj_meta(trial):
    dt = DecisionTreeRegressor(
        max_depth=trial.suggest_int('max_depth', 2, 8),
        min_samples_split=trial.suggest_int('min_samples_split', 2, 20),
        min_samples_leaf=trial.suggest_int('min_samples_leaf', 1, 15),
        random_state=42
    )
    # Validate the meta-learner to prevent overfitting on the base model predictions
    X_m_tr, X_m_v, y_m_tr, y_m_v = train_test_split(X_meta_train, y_all, test_size=0.2, random_state=42)
    dt.fit(X_m_tr, y_m_tr)
    return r2_score(y_m_v, dt.predict(X_m_v))

st_meta = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))

st_meta.optimize(obj_meta, n_trials=N_TRIALS, show_progress_bar=True)

bp_meta = st_meta.best_params
print(f"Best Meta-Learner Params: {bp_meta}")

"""Run 20 random seeds with the best hyperparameters"""

meta_blind_r2 = []

for seed in SEEDS:
    meta_model = DecisionTreeRegressor(**bp_meta, random_state=seed)
    meta_model.fit(X_meta_train, y_all)

    preds = meta_model.predict(X_meta_test)
    r2 = r2_score(y_test, preds)
    meta_blind_r2.append(r2)
    print(f"  Seed {seed:>5}: Blind R² = {r2:.4f}")

meta_mean = np.mean(meta_blind_r2)
meta_std = np.std(meta_blind_r2)
print(f"\nMeta-Learner Average Blind R²: {meta_mean:.4f} ± {meta_std:.4f}")

def score(y_true, y_pred):
    r2 = r2_score(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)

    non_zero_mask = y_true != 0
    if np.any(non_zero_mask):
        mape = np.mean(np.abs((y_true[non_zero_mask] - y_pred[non_zero_mask]) / y_true[non_zero_mask])) * 100
    else:
        mape = np.nan # Or 0, depending on desired behavior for all zeros

    corr = np.corrcoef(y_true, y_pred)[0, 1] if len(y_true) > 1 else np.nan
    return (r2, rmse, mae, mse, mape, corr)

X_meta_val = np.zeros((X_optuna_val.shape[0], 6))
model_names_list = ['XGB', 'LightGBM', 'CatBoost', 'AdaBoost', 'RF', 'DecisionTree']
for i, model_name in enumerate(model_names_list):
    model = all_seed_runs[model_name][42]['model']
    X_meta_val[:, i] = model.predict(X_optuna_val)

all_seed_runs['Meta_DT'] = {seed: {'params': bp_meta, 'metrics': {}} for seed in SEEDS}

print("\nEvaluating Meta-Learner across all metrics and seeds...")
for seed in tqdm(SEEDS, desc="Meta-DT Training"):
    meta_model = DecisionTreeRegressor(**bp_meta, random_state=seed)
    meta_model.fit(X_meta_train, y_all)

    all_seed_runs['Meta_DT'][seed]['metrics'] = {
        'Train': score(y_all, meta_model.predict(X_meta_train)),
        'Val':   score(y_optuna_val, meta_model.predict(X_meta_val)),
        'Blind': score(y_test, meta_model.predict(X_meta_test)),
    }

for model_name in ['XGB', 'LightGBM', 'CatBoost', 'AdaBoost', 'RF', 'DecisionTree']:
    model = all_seed_runs[model_name][42]['model'] # Get the loaded best model (seed 42)

    train_preds = model.predict(X_all_s)
    val_preds = model.predict(X_optuna_val)
    blind_preds = model.predict(X_test_s)

    train_scores = score(y_all, train_preds)
    val_scores = score(y_optuna_val, val_preds)
    blind_scores = score(y_test, blind_preds)

    for seed in SEEDS:
        if seed not in all_seed_runs[model_name]:
            all_seed_runs[model_name][seed] = {'params': {}, 'metrics': {}}
        all_seed_runs[model_name][seed]['metrics'] = {
            'Train': train_scores,
            'Val': val_scores,
            'Blind': blind_scores,
        }

print(" Meta model baseline - Meta decision tree with 5 models (Blind well across 20 random seeds\n")
print(f"  {'Model':>12} | {'R²':>13} | {'RMSE':>13} | {'MAE':>13} | {'MAPE (%)':>13} | {'Corr':>13}")

for m in all_seed_runs:
    v = np.array([all_seed_runs[m][s]['metrics']['Blind'] for s in SEEDS])
    mu, sd = v.mean(0), v.std(0)

    prefix = "► " if m == 'Meta_DT' else "  "

    print(f"{prefix}{m:>12} | {mu[0]:.4f}±{sd[0]:.4f} | {mu[1]:.2f}±{sd[1]:.2f} | {mu[2]:.2f}±{sd[2]:.2f} | {mu[4]:.3f}±{sd[4]:.3f} | {mu[5]:.4f}±{sd[5]:.4f}")

"""# 7. Neurips quality ablantion studies

## 7.1 Ablantian studies baselines

#### 7.1.1 Meta decision tree
"""

ALL_COLS = list(range(len(base_models))) # Assuming base_models was previously defined
base_names = ['XGB', 'LightGBM', 'CatBoost', 'AdaBoost', 'RF', 'DecisionTree']

# Helper function for consistent formatting of R^2 scores
def fmt(arr):
    return f"{arr.mean():.4f} \u00b1 {arr.std():.4f}"


def eval_meta_reoptimize_for_combo(cols, seed_list=SEEDS, num_optuna_trials=N_TRIALS):
    if not cols:
        return np.full(len(seed_list), np.nan), {}

    X_m_train_sub = X_meta_train[:, cols]
    X_m_test_sub = X_meta_test[:, cols]

    def obj_meta_sub(trial):
        dt = DecisionTreeRegressor(
            max_depth=trial.suggest_int('max_depth', 2, 8),
            min_samples_split=trial.suggest_int('min_samples_split', 2, 20),
            min_samples_leaf=trial.suggest_int('min_samples_leaf', 1, 15),
            random_state=42 # Fixed seed for Optuna's internal validation split reproducibility
        )
        # Use a portion of the *current combination's* meta-train data for Optuna's validation
        X_opt_tr, X_opt_v, y_opt_tr, y_opt_v = train_test_split(
            X_m_train_sub, y_all, test_size=0.2, random_state=42
        )
        dt.fit(X_opt_tr, y_opt_tr)
        return r2_score(y_opt_v, dt.predict(X_opt_v))

    # Create a unique study name/seed for each combination to ensure independence
    study_name = f"meta_dt_combo_{'_'.join(map(str, sorted(cols)))}_rand{np.random.randint(0,10000)}"
    # Use a simpler unique seed for sampler based on combination indices
    sampler_seed = 42 + sum(cols) if cols else 42
    optuna_study = optuna.create_study(study_name=study_name, direction='maximize',
                                       sampler=optuna.samplers.TPESampler(seed=sampler_seed),
                                       load_if_exists=False)
    optuna_study.optimize(obj_meta_sub, n_trials=num_optuna_trials, show_progress_bar=False)
    best_params_for_combo = optuna_study.best_params

    r2s = []
    for seed in seed_list:
        meta_model = DecisionTreeRegressor(**best_params_for_combo, random_state=seed)
        meta_model.fit(X_m_train_sub, y_all)
        r2s.append(r2_score(y_test, meta_model.predict(X_m_test_sub)))

    return np.array(r2s), best_params_for_combo

"""Calculate the baseline for 'ALL 5' models with Optuna re-optimization"""

baseline_r2, baseline_opt_params = eval_meta_reoptimize_for_combo(ALL_COLS, seed_list=SEEDS, num_optuna_trials=N_TRIALS)
baseline_mean_r2 = baseline_r2.mean()
print(f"  {'ALL 5 (baseline)':40s} {fmt(baseline_r2):>16}  {'—':>18}")

all_combinations_results = []

"""Add the baseline (all 5 models) to the results list first"""

all_combinations_results.append({
    'name': "+".join(base_names[k] for k in ALL_COLS),
    'r': len(ALL_COLS),
    'mean_r2': baseline_mean_r2,
    'std_r2': baseline_r2.std(),
    'delta_from_baseline': 0.0, # By definition
    'optimized_params': baseline_opt_params
})

"""Iterate through combinations of sizes from 1 to 5"""

for r in tqdm(range(1, len(base_names) + 1), desc="Evaluating Combinations"):
    for combo_idx_tuple in combinations(ALL_COLS, r):
        combo_idx = list(combo_idx_tuple)

        # Skip the 'ALL 5' combination as it was already added as baseline
        if set(combo_idx) == set(ALL_COLS):
            continue

        r2s, best_params_for_this_combo = eval_meta_reoptimize_for_combo(combo_idx, seed_list=SEEDS, num_optuna_trials=N_TRIALS)
        mean_r2 = r2s.mean()
        std_r2 = r2s.std()

        combo_name = "+".join(base_names[k] for k in combo_idx)
        delta_r2 = mean_r2 - baseline_mean_r2

        all_combinations_results.append({
            'name': combo_name,
            'r': r,
            'mean_r2': mean_r2,
            'std_r2': std_r2,
            'delta_from_baseline': delta_r2,
            'optimized_params': best_params_for_this_combo
        })

"""Group results by size and then sort by mean_r2 within each group"""

grouped_results = {}
for result in all_combinations_results:
    grouped_results.setdefault(result['r'], []).append(result)

for r in sorted(grouped_results.keys()):
    print(f"\n  Combinations of {r} models (sorted by R²):")
    print(f"  {'Configuration':40s} {'Blind R²':>16}  {'Δ R² (vs All 5)':>18}")
    print("  " + "—" * 78)

    sorted_group = sorted(grouped_results[r], key=lambda x: x['mean_r2'], reverse=True)
    for res in sorted_group:
        blind_r2_formatted = f"{res['mean_r2']:.4f} \u00b1 {res['std_r2']:.4f}"
        print(f"  {res['name']:40s} {blind_r2_formatted:>16}  {res['delta_from_baseline']:>+18.4f}")

print("\n" + "═" * 80)
print("  Analysis of R² Differences from Baseline (All 6 Models) - Sorted by Blind R² Mean (Smallest to Largest):")
print("  " + "—" * 80)

"""Sort all results by mean_r2 in ascending order"""

sorted_by_mean_r2 = sorted(all_combinations_results, key=lambda x: x['mean_r2'])

print(f"  {'Configuration':40s} {'Blind R² Mean':>16}  {'Δ R² (vs All 6)':>18}")
for res in sorted_by_mean_r2:
    print(f"  {res['name']:40s} {res['mean_r2']:.4f}              {res['delta_from_baseline']:>+18.4f}")

sorted_by_r2 = sorted(all_combinations_results, key=lambda x: x['mean_r2'], reverse=True)
top_3_combinations = sorted_by_r2[:3]

print("  Top 3 Meta decision tree hyperparameters combinations")

for i, combo in enumerate(top_3_combinations):
    print(f"\n  Rank {i+1}: {combo['name']} (Blind R² Mean: {combo['mean_r2']:.4f})")
    print(f"  Meta-Tree Hyperparameters: {combo['optimized_params']}")

"""### 7.1.2 Linear combination

Instantiate, train, and make predictions
"""

linear_meta_model = LinearRegression()
linear_meta_model.fit(X_meta_train, y_all)
linear_preds = linear_meta_model.predict(X_meta_test)

"""Evaluate the performance and store results(Linear regression is deterministic so all seeds have the same score)"""

linear_r2 = r2_score(y_test, linear_preds)
linear_rmse = np.sqrt(mean_squared_error(y_test, linear_preds))
linear_mae = mean_absolute_error(y_test, linear_preds)

print(f"Blind R² (Full Linear Combo): {linear_r2:.4f}")
print(f"Blind RMSE (Full Linear Combo): {linear_rmse:.2f}")
print(f"Blind MAE (Full Linear Combo): {linear_mae:.2f}")

print("\nLearned Weights (Coefficients) for All 5 Base Models:")
for i, name in enumerate(base_names):
    print(f"  {name}: {linear_meta_model.coef_[i]:.4f}")

print(f"  Intercept: {linear_meta_model.intercept_:.4f}")

all_seed_runs['Linear_Combo'] = {}
linear_scores = score(y_test, linear_preds)

for seed in SEEDS:
    all_seed_runs['Linear_Combo'][seed] = {
        'params': {'model': 'LinearRegression', 'optimized_weights': linear_meta_model.coef_.tolist()},
        'metrics': {
            'Train': score(y_all, linear_meta_model.predict(X_meta_train)),
            'Val': score(y_optuna_val, linear_meta_model.predict(X_meta_val)),
            'Blind': linear_scores,
        }
    }
print("═"*80)

"""## 7.2 Advanced ablantion studies"""

print("ABLATION B · LINEAR COMBINATION CONTRIBUTIONS")
print(f"  {'Configuration':40s} {'Blind R²':>16}  {'Δ R² (vs All 5 LC)':>18}")
print("─" * 80)

# Baseline for All 5 models linear combination (already computed in previous cell)
linear_baseline_r2 = all_seed_runs['Linear_Combo'][SEEDS[0]]['metrics']['Blind'][0]
# Corrected line: Format mean and std into a single string, then align it
linear_baseline_r2_formatted = f"{linear_baseline_r2:.4f} \u00b1 {0.0000:.4f}"
print(f"  {'ALL 5 (Linear Combo baseline)':40s} {linear_baseline_r2_formatted:>16}  {'—':>18}")

def eval_linear_combo_for_combo(cols):
    if not cols:
        return np.nan, [], np.nan # No models, no score

    X_m_train_sub = X_meta_train[:, cols]
    X_m_test_sub = X_meta_test[:, cols]

    lin_model = LinearRegression()
    lin_model.fit(X_m_train_sub, y_all)
    preds = lin_model.predict(X_m_test_sub)

    r2 = r2_score(y_test, preds)
    return r2, lin_model.coef_.tolist(), lin_model.intercept_

linear_combinations_results = []

# Iterate through combinations of sizes from 2 to 5 (excluding individual models)
for r in tqdm(range(2, len(base_names) + 1), desc="Evaluating Linear Combinations"):
    for combo_idx_tuple in combinations(ALL_COLS, r):
        combo_idx = list(combo_idx_tuple)

        mean_r2, coefficients, intercept = eval_linear_combo_for_combo(combo_idx)

        combo_name = "+".join(base_names[k] for k in combo_idx)
        delta_r2 = mean_r2 - linear_baseline_r2

        linear_combinations_results.append({
            'name': combo_name,
            'r': r,
            'mean_r2': mean_r2,
            'std_r2': 0.0, # LinearRegression is deterministic
            'delta_from_baseline': delta_r2,
            'coefficients': coefficients,
            'intercept': intercept
        })

# Group results by size and then sort by mean_r2 within each group
grouped_linear_results = {}
for result in linear_combinations_results:
    grouped_linear_results.setdefault(result['r'], []).append(result)

for r in sorted(grouped_linear_results.keys()):
    print(f"\n  Combinations of {r} models (sorted by R²):")
    print(f"  {'Configuration':40s} {'Blind R²':>16}  {'Δ R² (vs All 5 LC)':>18}")
    print("  " + "─" * 78)

    sorted_group = sorted(grouped_linear_results[r], key=lambda x: x['mean_r2'], reverse=True)
    for res in sorted_group:
        blind_r2_formatted = f"{res['mean_r2']:.4f} \u00b1 {res['std_r2']:.4f}"
        print(f"  {res['name']:40s} {blind_r2_formatted:>16}  {res['delta_from_baseline']:>+18.4f}")
        print(f"    Weights: {', '.join([f'{base_names[combo_idx_tuple[i]]}={coeff:.2f}' for i, coeff in enumerate(res['coefficients'])])}, Intercept={res['intercept']:.2f}")

print("\n" + "═" * 80)
print("  Analysis of Linear Combination R² Differences from Baseline (All 5 Models) - Sorted by Blind R² Mean (Smallest to Largest):")
print("  " + "─" * 80)

# Sort all results by mean_r2 in ascending order
sorted_by_mean_r2_linear = sorted(linear_combinations_results, key=lambda x: x['mean_r2'])

print(f"  {'Configuration':40s} {'Blind R² Mean':>16}  {'Δ R² (vs All 5 LC)':>18}")
print("  " + "─" * 78)
for res in sorted_by_mean_r2_linear:
    print(f"  {res['name']:40s} {res['mean_r2']:.4f}              {res['delta_from_baseline']:>+18.4f}")

print("═" * 80)

sorted_linear_results = sorted(linear_combinations_results, key=lambda x: x['mean_r2'], reverse=True)
top_5_linear_combinations = sorted_linear_results[:5]

print("\n" + "═"*80)
print("  TOP 5 LINEAR COMBINATION WEIGHTS (BY BLIND R² MEAN)")
print("═"*80)

for i, combo in enumerate(top_5_linear_combinations):
    print(f"\n  Rank {i+1}: {combo['name']} (Blind R² Mean: {combo['mean_r2']:.4f})")
    # Reconstruct the combo_idx to correctly map weights to base model names
    # This assumes base_names are indexed correctly with ALL_COLS positions
    current_combo_base_indices = [base_names.index(name) for name in combo['name'].split('+')]

    print(f"  Learned Weights (Coefficients) for Base Models:")
    for j, coeff in enumerate(combo['coefficients']):
        print(f"    {base_names[current_combo_base_indices[j]]}: {coeff:.4f}")
    print(f"  Intercept: {combo['intercept']:.4f}")

print("═"*80)

"""Hyperparameter sensitivity"""

sorted_dt_results = sorted(all_combinations_results, key=lambda x: x['mean_r2'], reverse=True)
best_dt_combo = sorted_dt_results[0] # Assuming this is the 'LightGBM' one
best_dt_params = best_dt_combo['optimized_params']
best_dt_combo_name = best_dt_combo['name']
best_dt_combo_mean_r2 = best_dt_combo['mean_r2']


# Determine the columns to be used for the best DT combination
best_dt_combo_cols = [base_names.index(name) for name in best_dt_combo_name.split('+')]
X_meta_train_dt_sub = X_meta_train[:, best_dt_combo_cols]
X_meta_test_dt_sub = X_meta_test[:, best_dt_combo_cols]

def sweep_dt_sensitivity(param_name, values, base_params, X_train_sub, X_test_sub):
    print(f"\n  [{param_name}] sweep:")
    results = []
    for v in values:
        p = base_params.copy()
        if param_name == 'max_depth' and v is None:
            if 'max_depth' in p:
                del p['max_depth']
        else:
            p[param_name] = v

        r2s = []
        for seed in SEEDS:
            dt = DecisionTreeRegressor(**p, random_state=seed)
            dt.fit(X_train_sub, y_all)
            r2s.append(r2_score(y_test, dt.predict(X_test_sub)))
        arr = np.array(r2s)
        current_best = " ◄" if v == base_params.get(param_name) else ""
        print(f"    {param_name}={str(v):>4s}  Blind R²={fmt(arr)}{current_best}")
        results.append((v, arr))
    return results

depth_res_dt = sweep_dt_sensitivity('max_depth',        [1, 2, 3, 4, 5, 6, 8, 10, None], best_dt_params, X_meta_train_dt_sub, X_meta_test_dt_sub)
leaf_res_dt  = sweep_dt_sensitivity('min_samples_leaf',  [1, 2, 5, 10, 15, 20, 50], best_dt_params, X_meta_train_dt_sub, X_meta_test_dt_sub)
split_res_dt = sweep_dt_sensitivity('min_samples_split', [2, 5, 10, 15, 20, 30], best_dt_params, X_meta_train_dt_sub, X_meta_test_dt_sub)

"""Training data efficiency"""

fractions = [0.05, 0.1, 0.2, 0.3, 0.5, 0.7, 0.85, 1.0]

# --- Decision Tree Meta-Learner Learning Curve ---
print("\n--- Decision Tree Meta-Learner ---")
print(f"  {'Fraction':>10}  {'N samples':>10}  {'Blind R²':>16}")
print("─" * 45)
dt_lc_results = []
for frac in fractions:
    r2s = []
    for seed in SEEDS:
        n = int(frac * len(X_meta_train_dt_sub)) # Use the subset length for DT
        idx = np.random.RandomState(seed).choice(len(X_meta_train_dt_sub), n, replace=False)
        dt = DecisionTreeRegressor(**best_dt_params, random_state=seed) # Use best_dt_params
        dt.fit(X_meta_train_dt_sub[idx], y_all[idx]) # Use subsetted data
        r2s.append(r2_score(y_test, dt.predict(X_meta_test_dt_sub))) # Use subsetted data
    arr = np.array(r2s)
    dt_lc_results.append(arr)
    print(f"  {frac:>10.0%}  {n:>10,}  {fmt(arr):>16}")

# Get the best LR combination from the previous results
best_lr_combo = sorted(linear_combinations_results, key=lambda x: x['mean_r2'], reverse=True)[0]
best_lr_name = best_lr_combo['name']

print(f"\n--- Linear Regression Meta-Learner ({best_lr_name} Best Combo) ---")
print(f"  {'Fraction':>10}  {'N samples':>10}  {'Blind R²':>16}")
print("─" * 45)
lr_lc_results = []

# Dynamically get indices for the best combo
best_lr_cols = [base_names.index(name) for name in best_lr_name.split('+')]

X_meta_train_lr_sub = X_meta_train[:, best_lr_cols]
X_meta_test_lr_sub = X_meta_test[:, best_lr_cols]

for frac in fractions:
    r2s = []
    for seed in SEEDS:
        # Subsample based on the length of the specific combination's meta-features
        n = int(frac * len(X_meta_train_lr_sub))
        idx = np.random.RandomState(seed).choice(len(X_meta_train_lr_sub), n, replace=False)

        lr_model = LinearRegression()
        # Train LR on subsampled data using the best combo's features
        lr_model.fit(X_meta_train_lr_sub[idx], y_all[idx])
        # Evaluate on the full best combo's predictions from the test set
        r2s.append(r2_score(y_test, lr_model.predict(X_meta_test_lr_sub)))
    arr = np.array(r2s)
    lr_lc_results.append(arr)
    print(f"  {frac:>10.0%}  {n:>10,}  {fmt(arr):>16}")

"""# 8. Deciding on the best meta stacking"""

metric_names = ['R²', 'RMSE', 'MAE', 'MSE', 'MAPE (%)', 'Corr']

best_dt_cols = [base_names.index(n) for n in best_dt_combo['name'].split('+')]

dt_all_metrics = []
for seed in SEEDS:
    dt = DecisionTreeRegressor(**best_dt_combo['optimized_params'], random_state=seed)
    dt.fit(X_meta_train[:, best_dt_cols], y_all)
    preds = dt.predict(X_meta_test[:, best_dt_cols])
    dt_all_metrics.append(score(y_test, preds))

dt_arr = np.array(dt_all_metrics)

print("═" * 70)
print(f" BEST DT META-LEARNER: {best_dt_combo['name']}")
print(f" Params: {best_dt_combo['optimized_params']}")
print(f"  {'Metric':>12} | {'Mean':>12} | {'Std':>12}")
print("─" * 70)
for i, name in enumerate(metric_names):
    print(f"  {name:>12} | {dt_arr[:, i].mean():>12.4f} | {dt_arr[:, i].std():>12.4f}")

best_lr_combo = sorted(linear_combinations_results, key=lambda x: x['mean_r2'], reverse=True)[0]
best_lr_cols = [base_names.index(n) for n in best_lr_combo['name'].split('+')]

lr_model = LinearRegression()
lr_model.fit(X_meta_train[:, best_lr_cols], y_all)
lr_preds = lr_model.predict(X_meta_test[:, best_lr_cols])
lr_metrics = score(y_test, lr_preds)

print(f"\n{'═' * 70}")
print(f" BEST LINEAR COMBO META-LEARNER: {best_lr_combo['name']}")
print(f" Weights: {dict(zip(best_lr_combo['name'].split('+'), best_lr_combo['coefficients']))}")
print(f" Intercept: {best_lr_combo['intercept']:.4f}")
print(f"  {'Metric':>12} | {'Value':>12}")
print("─" * 70)
for i, name in enumerate(metric_names):
    print(f"  {name:>12} | {lr_metrics[i]:>12.4f}")

with open('/content/optimal_models_parameters/best_models_summary.json', 'r') as f:
    summary = json.load(f)

print(json.dumps(summary, indent=2))

"""# 9. Graphs"""

SINGLE_COL   = 3.5
ONE_HALF_COL = 5.5
FULL_PAGE    = 7.5

plt.rcParams.update({
    'figure.dpi': 150, 'savefig.dpi': 600,
    'font.family': 'serif',
    'font.serif': ['FreeSerif', 'DejaVu Serif'],
    'font.size': 8, 'axes.labelsize': 9,
    'xtick.labelsize': 7, 'ytick.labelsize': 7, 'legend.fontsize': 7,
    'axes.linewidth': 0.6, 'lines.linewidth': 1.0, 'grid.linewidth': 0.4,
    'xtick.major.width': 0.5, 'ytick.major.width': 0.5,
    'xtick.minor.width': 0.3, 'ytick.minor.width': 0.3,
    'xtick.direction': 'in', 'ytick.direction': 'in',
    'xtick.minor.visible': False, 'ytick.minor.visible': True,
    'xtick.top': True, 'ytick.right': True,
    'legend.frameon': False,
    'savefig.bbox': 'tight', 'savefig.pad_inches': 0.02,
    'savefig.transparent': False,
})

CB = ['#0077BB', '#CC3311', '#009988', '#EE7733', '#33BBEE', '#EE3377', '#BBBBBB']

"""Best Decision Tree Meta-Learner"""

best_dt_cols = [base_names.index(n) for n in best_dt_combo['name'].split('+')]
dt_meta = DecisionTreeRegressor(**best_dt_combo['optimized_params'], random_state=42)
dt_meta.fit(X_meta_train[:, best_dt_cols], y_all)
y_pred_dt = dt_meta.predict(X_meta_test[:, best_dt_cols])

r2_dt   = r2_score(y_test, y_pred_dt)
rmse_dt = np.sqrt(mean_squared_error(y_test, y_pred_dt))
mae_dt  = mean_absolute_error(y_test, y_pred_dt)

"""Best Linear Regression Meta-Learner"""

best_lr_combo_final = sorted(linear_combinations_results, key=lambda x: x['mean_r2'], reverse=True)[0]
best_lr_cols = [base_names.index(n) for n in best_lr_combo_final['name'].split('+')]
lr_meta = LinearRegression()
lr_meta.fit(X_meta_train[:, best_lr_cols], y_all)
y_pred_lr = lr_meta.predict(X_meta_test[:, best_lr_cols])

r2_lr   = r2_score(y_test, y_pred_lr)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
mae_lr  = mean_absolute_error(y_test, y_pred_lr)

"""Base model predictions"""

base_preds = {}
for i, bname in enumerate(base_names):
    base_preds[bname] = all_seed_runs[bname][42]['model'].predict(X_test_s)

"""Depth column"""

dcol  = next((c for c in ['DEPTH', 'depth', 'tvd'] if c in blind_df.columns), None)
depth = blind_df[dcol].values if dcol else np.arange(len(y_test))

print(f"Best DT Meta ({best_dt_combo['name']}): R2={r2_dt:.4f}  RMSE={rmse_dt:.1f}")
print(f"Best LR Meta ({best_lr_combo_final['name']}): R2={r2_lr:.4f}  RMSE={rmse_lr:.1f}")

"""## 9.1 Blind-Well Composite Log"""

track_spec = [
    ('Gamma Ray',       ['gr', 'GR'],                              'API'),
    ('Volume of Shale', ['vsh', 'VSH'],                            '$V_{sh}$ (v/v)'),
    ('Sonic \& NCT',     [('dt', 'DT'), ('dt_nct', 'NCT')],        '$\Delta t$ ($\mu$s/ft)'),
    ('Resistivity',     ['res_deep', 'RES_DEEP', 'rt', 'ild'],    'Res ($\Omega\cdot$m)'),
]

fig, axes = plt.subplots(1, 5, figsize=(FULL_PAGE, 4.8), sharey=True)

for i, (title, cands, unit) in enumerate(track_spec):
    ax = axes[i]
    if i == 2:
        lstyles = ['-', '--']
        for j, (cname, lbl) in enumerate(cands):
            if cname in blind_df.columns:
                ax.plot(blind_df[cname].values, depth, color=CB[j], ls=lstyles[j], lw=0.8, label=lbl)
    else:
        for c in cands:
            if c in blind_df.columns:
                ax.plot(blind_df[c].values, depth, color=CB[i], lw=0.8, label=c.upper())
                break
    ax.set_title(title, fontsize=8, pad=4)
    ax.set_xlabel(unit)
    ax.legend(loc='lower left')
    ax.invert_yaxis()
    ax.grid(True, alpha=0.25)

ax5 = axes[4]
pres_curves = [('hp', 'HP', CB[4], '-'), ('ob', 'OB', CB[6], '--'), ('ppp', 'PP (Eaton)', CB[1], '-.')]
for c, lbl, col, ls in pres_curves:
    if c in blind_df.columns:
        ax5.plot(blind_df[c].values, depth, color=col, ls=ls, lw=0.8, label=lbl)
ax5.plot(y_pred_dt, depth, color=CB[5], ls='-',  lw=1.0, label='DT Meta')
ax5.plot(y_pred_lr, depth, color=CB[2], ls='--', lw=1.0, label='LR Meta')
ax5.set_title('Pressure Profiles', fontsize=8, pad=4)
ax5.set_xlabel('Pressure (psi)')
ax5.legend(loc='lower left')
ax5.invert_yaxis()
ax5.grid(True, alpha=0.25)
axes[0].set_ylabel('Depth (m)')

fig.savefig('welllog_blind.tiff', dpi=600)
fig.savefig('welllog_blind.png', dpi=600)
fig.savefig('welllog_blind.eps')
plt.show()

"""## 9.2 Actual vs Predicted Scatter"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(FULL_PAGE, 3.5))

for ax, yp, r2v, rmv, mav, lbl, clr in [
    (ax1, y_pred_dt, r2_dt, rmse_dt, mae_dt, f'DT Meta ({best_dt_combo["name"]})', CB[0]),
    (ax2, y_pred_lr, r2_lr, rmse_lr, mae_lr, f'LR Meta ({best_lr_combo_final["name"]})', CB[2]),
]:
    ax.scatter(y_test, yp, s=4, alpha=0.35, color=clr, edgecolors='none', rasterized=True, zorder=2)
    lims = [min(y_test.min(), yp.min()) * 0.95, max(y_test.max(), yp.max()) * 1.05]
    ax.plot(lims, lims, color=CB[1], ls='--', lw=0.8, label='1:1 line', zorder=3)
    ax.set(xlim=lims, ylim=lims, aspect='equal',
           xlabel='Actual pore pressure (psi)', ylabel='Predicted pore pressure (psi)')
    ax.text(0.05, 0.92,
            f'$R^2$ = {r2v:.4f}\nRMSE = {rmv:.1f} psi\nMAE = {mav:.1f} psi',
            transform=ax.transAxes, fontsize=6.5, verticalalignment='top',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='#CCC', alpha=0.9))
    ax.set_title(lbl, fontsize=8)
    ax.legend(loc='lower right')
    ax.grid(True, alpha=0.25)

fig.savefig('scatter_both.tiff', dpi=600)
fig.savefig('scatter_both.png', dpi=600)
fig.savefig('scatter_both.eps')
plt.show()

"""## 9.3 Residual Analysis"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(FULL_PAGE, 3.0))

for ax, yp, lbl, clr in [
    (ax1, y_pred_dt, f'DT Meta', CB[3]),
    (ax2, y_pred_lr, f'LR Meta', CB[2]),
]:
    res  = y_test - yp
    rho  = np.corrcoef(yp, res)[0, 1]
    sig  = res.std()
    sidx = np.argsort(yp)
    win  = max(len(res) // 50, 10)
    ma   = pd.Series(res[sidx]).rolling(win, center=True).mean()

    ax.scatter(yp, res, s=4, alpha=0.3, color=clr, edgecolors='none', rasterized=True, zorder=2)
    ax.axhline(0, color='k', lw=0.6, zorder=1)
    ax.plot(yp[sidx], ma.values, color=CB[2], ls='-', lw=1.2, label='Moving avg', zorder=3)
    ax.axhline( sig, color=CB[1], ls='--', lw=0.7, label=f'$\\pm\\sigma$ = {sig:.1f}')
    ax.axhline(-sig, color=CB[1], ls='--', lw=0.7)
    ax.set(xlabel='Predicted (psi)', ylabel='Residual (psi)')
    ax.set_title(f'{lbl}  ($\\rho$ = {rho:.3f})', fontsize=8)
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, 1.22), ncol=2)
    ax.grid(True, alpha=0.25)

fig.savefig('residuals_both.tiff', dpi=600)
fig.savefig('residuals_both.png', dpi=600)
fig.savefig('residuals_both.eps')
plt.show()

"""## 9.4 R² by Depth Interval"""

if dcol:
    dmin, dmax = depth.min(), depth.max()
    thirds = np.linspace(dmin, dmax, 4)
    tags = ['Shallow', 'Medium', 'Deep']

    fig, ax = plt.subplots(figsize=(ONE_HALF_COL, 3.0))

    meta_specs = [
        (y_pred_dt, 'DT Meta', '#0077BB', 'o', '-', 12),
        (y_pred_lr, 'LR Meta', '#CC3311', 's', '--', 10),
    ]

    for yp, lbl, clr, mk, ls, ms in meta_specs:
        centers, r2s = [], []
        for j in range(3):
            mask = (depth >= thirds[j]) & (depth < thirds[j+1] + (1 if j == 2 else 0))
            if mask.sum() > 10:
                r2s.append(r2_score(y_test[mask], yp[mask]))
                centers.append((thirds[j] + thirds[j+1]) / 2)
        ax.plot(centers, r2s, marker=mk, ls=ls, color=clr, lw=1.5, ms=ms,
                markerfacecolor='white', markeredgewidth=1.8, markeredgecolor=clr, label=lbl)
        y_off = 12 if mk == 'o' else -18
        for c, r in zip(centers, r2s):
            ax.annotate(f'{r:.3f}', (c, r), textcoords='offset points',
                        xytext=(0, y_off), ha='center', fontsize=7, fontweight='bold', color=clr)

    labels_d = [f'{tags[j]}\n({thirds[j]:.0f}\u2013{thirds[j+1]:.0f} m)' for j in range(3)]
    ax.set_xticks(centers)
    ax.set_xticklabels(labels_d)
    ax.set_ylabel('$R^2$')
    ax.set_ylim(0, 1.15)
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, 1.18), ncol=2)
    ax.grid(True, alpha=0.25)

    fig.savefig('depth_perf.tiff', dpi=600)
    fig.savefig('depth_perf.png', dpi=600)
    fig.savefig('depth_perf.eps')
    plt.show()

"""## 9.5 Model Performance Comparison"""

compare_models = {}
for bname in base_names:
    p = base_preds[bname]
    compare_models[bname] = score(y_test, p)
dt_label = f'DT Meta ({best_dt_combo["name"]})'
lr_label = f'LR Meta ({best_lr_combo_final["name"]})'
compare_models[dt_label] = score(y_test, y_pred_dt)
compare_models[lr_label] = score(y_test, y_pred_lr)

sorted_models = sorted(compare_models.items(), key=lambda x: x[1][0], reverse=True)
names_9 = [x[0] for x in sorted_models]
r2_vals = [x[1][0] for x in sorted_models]

bar_styles = {
    dt_label:       ('#0077BB', ''),
    lr_label:       ('#CC3311', ''),
    'XGB':          ('#EE7733', '//'),
    'LightGBM':     ('#33BBEE', '\\\\'),
    'CatBoost':     ('#009988', '..'),
    'AdaBoost':     ('#EE3377', 'xx'),
    'RF':           ('#BBBBBB', '--'),
    'DecisionTree': ('#AA3377', 'oo'),
}

fig, ax = plt.subplots(figsize=(ONE_HALF_COL, 3.5))
y_pos = np.arange(len(names_9))

for i, name in enumerate(names_9):
    clr, hatch = bar_styles.get(name, ('#BBBBBB', ''))
    ax.barh(i, r2_vals[i], color=clr, hatch=hatch, edgecolor='white',
            height=0.65, linewidth=0.5)
    ax.text(r2_vals[i] + 0.008, i, f'{r2_vals[i]:.4f}', va='center', fontsize=6.5,
            fontweight='bold')

ax.set_yticks(y_pos)
ax.set_yticklabels(names_9, fontsize=7)
ax.invert_yaxis()
ax.set_xlabel('Blind $R^2$')
ax.set_xlim(0, max(r2_vals) * 1.12)
ax.grid(True, axis='x', alpha=0.25)

fig.savefig('model_comparison.tiff', dpi=600)
fig.savefig('model_comparison.png', dpi=600)
fig.savefig('model_comparison.eps')
plt.show()

# Build a comparison dict: base models from summary + meta-learners from ablation
compare_models = {}

# Base models from the optimal notebook (via summary JSON)
for bname, info in summary.items():
    m = info['metrics']['Blind']
    compare_models[bname] = (m['r2'], m['rmse'], m['mae'], m['mse'], m['mape'], m['corr'])

# Meta-learners from this ablation notebook
dt_label = f'DT Meta ({best_dt_combo["name"]})'
lr_label = f'LR Meta ({best_lr_combo_final["name"]})'
compare_models[dt_label] = score(y_test, y_pred_dt)
compare_models[lr_label] = score(y_test, y_pred_lr)

print(f"  {'Model':>30} | {'R²':>8} | {'RMSE':>8} | {'MAE':>8} | {'MAPE':>8} | {'Corr':>8}")
for name, vals in sorted(compare_models.items(), key=lambda x: x[1][0], reverse=True):
    print(f"  {name:>30} | {vals[0]:>8.4f} | {vals[1]:>8.2f} | {vals[2]:>8.2f} | {vals[4]:>8.3f} | {vals[5]:>8.4f}")

"""## 9.6 Prediction Correlation Matrix"""

all_preds_dict = {**base_preds, 'DT Meta': y_pred_dt, 'LR Meta': y_pred_lr}
pred_df = pd.DataFrame(all_preds_dict)
corr = pred_df.corr()

fig, ax = plt.subplots(figsize=(SINGLE_COL + 1, SINGLE_COL + 1))
mask = np.triu(np.ones_like(corr, dtype=bool), k=1)
cmap = plt.cm.RdYlBu_r
im = ax.imshow(corr.values, cmap=cmap, vmin=0.8, vmax=1.0, aspect='equal')

labels_10 = list(corr.columns)
ax.set_xticks(range(len(labels_10)))
ax.set_xticklabels(labels_10, rotation=45, ha='right', fontsize=6.5)
ax.set_yticks(range(len(labels_10)))
ax.set_yticklabels(labels_10, fontsize=6.5)

for i in range(len(labels_10)):
    for j in range(len(labels_10)):
        ax.text(j, i, f'{corr.values[i, j]:.3f}', ha='center', va='center', fontsize=5.5,
                color='white' if corr.values[i, j] < 0.88 else 'black')

cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
cbar.ax.tick_params(labelsize=6)

fig.savefig('correlation_matrix.tiff', dpi=600)
fig.savefig('correlation_matrix.png', dpi=600)
fig.savefig('correlation_matrix.eps')
plt.show()

"""## 9.7 Base vs Meta Scatter Comparison"""

best_base_name = max(base_preds, key=lambda n: r2_score(y_test, base_preds[n]))
y_pred_best_base = base_preds[best_base_name]
r2_bb = r2_score(y_test, y_pred_best_base)

fig11, axes_11 = plt.subplots(1, 3, figsize=(FULL_PAGE, 2.8))
specs_11_yp = [y_pred_best_base, y_pred_dt, y_pred_lr]
specs_11_lbl = [f'Best Base ({best_base_name})', 'DT Meta', 'LR Meta']
specs_11_r2 = [r2_bb, r2_dt, r2_lr]
specs_11_clr = [CB[6], CB[0], CB[2]]

for idx_11 in range(3):
    ax = axes_11[idx_11]
    yp = specs_11_yp[idx_11]
    lbl = specs_11_lbl[idx_11]
    r2v = specs_11_r2[idx_11]
    clr = specs_11_clr[idx_11]
    ax.scatter(y_test, yp, s=4, alpha=0.35, color=clr, edgecolors='none', rasterized=True)
    lo = min(y_test.min(), yp.min()) * 0.95
    hi = max(y_test.max(), yp.max()) * 1.05
    ax.plot([lo, hi], [lo, hi], color=CB[1], ls='--', lw=0.8)
    ax.set_xlim(lo, hi)
    ax.set_ylim(lo, hi)
    ax.set_aspect('equal')
    ax.set_xlabel('Actual (psi)')
    ax.set_ylabel('Predicted (psi)')
    ax.set_title(f'{lbl}\n$R^2$ = {r2v:.4f}', fontsize=7)
    ax.grid(True, alpha=0.25)

fig11.savefig('base_vs_meta.tiff', dpi=600)
fig11.savefig('base_vs_meta.png', dpi=600)
fig11.savefig('base_vs_meta.eps')
plt.show()

"""## 9.8 Error Distribution Histograms"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(FULL_PAGE, 2.8))

for ax, yp, lbl, clr_main, clr_base in [
    (ax1, y_pred_dt, 'DT Meta', CB[0], CB[6]),
    (ax2, y_pred_lr, 'LR Meta', CB[2], CB[6]),
]:
    err_meta = y_test - yp
    err_base = y_test - y_pred_best_base
    bins = np.linspace(min(err_meta.min(), err_base.min()),
                       max(err_meta.max(), err_base.max()), 50)

    ax.hist(err_base, bins=bins, alpha=0.5, color=clr_base, label=f'Best Base ({best_base_name})',
            density=True, edgecolor='white', linewidth=0.3)
    ax.hist(err_meta, bins=bins, alpha=0.6, color=clr_main, label=lbl,
            density=True, edgecolor='white', linewidth=0.3)

    ax.axvline(0, color='k', ls='-', lw=0.6)
    ax.set(xlabel='Prediction error (psi)', ylabel='Density')
    ax.set_title(f'{lbl}  ($\\sigma$ = {err_meta.std():.1f} psi)', fontsize=8)
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, 1.22), ncol=2, fontsize=6)
    ax.grid(True, alpha=0.25)

fig.savefig('error_distributions.tiff', dpi=600)
fig.savefig('error_distributions.png', dpi=600)
fig.savefig('error_distributions.eps')
plt.show()

"""## 9.9 Optuna Visualization — DT Meta-Learner Hyperparameter Search"""

def obj_meta_viz(trial):
    dt = DecisionTreeRegressor(
        max_depth=trial.suggest_int('max_depth', 2, 8),
        min_samples_split=trial.suggest_int('min_samples_split', 2, 20),
        min_samples_leaf=trial.suggest_int('min_samples_leaf', 1, 15),
        random_state=42)
    X_m_tr, X_m_v, y_m_tr, y_m_v = train_test_split(
        X_meta_train[:, best_dt_cols], y_all, test_size=0.2, random_state=42)
    dt.fit(X_m_tr, y_m_tr)
    return r2_score(y_m_v, dt.predict(X_m_v))

viz_study = optuna.create_study(direction='maximize',
                                sampler=optuna.samplers.TPESampler(seed=42))
viz_study.optimize(obj_meta_viz, n_trials=N_TRIALS, show_progress_bar=True)

optuna_names = ['optuna_dt_history', 'optuna_dt_importance', 'optuna_dt_parallel', 'optuna_dt_contour']
optuna_fns = [plot_optimization_history, plot_param_importances, plot_parallel_coordinate, plot_contour]
optuna_sizes = [(ONE_HALF_COL, 2.8), (SINGLE_COL, 2.8), (FULL_PAGE, 3.0), (ONE_HALF_COL, 4.0)]

for i in tqdm(range(len(optuna_fns)), desc="Optuna Plots"):
    try:
        optuna_fns[i](viz_study)
        gcf = plt.gcf()
        gcf.set_size_inches(optuna_sizes[i])
        gcf.savefig(f'{optuna_names[i]}.tiff', dpi=600)
        gcf.savefig(f'{optuna_names[i]}.png', dpi=600)
        gcf.savefig(f'{optuna_names[i]}.eps')
        plt.show()
    except Exception as e:
        print(f"  Skipped {optuna_names[i]}: {e}")