# -*- coding: utf-8 -*-
"""all_baselines.ipynb

Automatically generated by Colab.

# 1. Installing libraries
"""

!pip install uv

!uv pip install gdown torch pytorch_lightning xgboost optuna lightgbm catboost

"""# 2. Importing libraries and taking configurations"""

import warnings
import joblib
import gdown
import numpy as np
import pandas as pd
from scipy.stats import ks_2samp

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
import xgboost as xgb
import lightgbm as lgb
import catboost as cb

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset, random_split

import pytorch_lightning as pl
from pytorch_lightning.callbacks import EarlyStopping, ModelCheckpoint

import optuna

optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings('ignore')
np.random.seed(42); torch.manual_seed(42)
pl.seed_everything(42, workers=True)

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"PyTorch {torch.__version__} | PL {pl.__version__} | {DEVICE}")

SEEDS = [42, 137, 256, 1024, 7, 314, 999, 2048, 55, 8080]

N_TRIALS = 50

"""#3. Importing wells data"""

dfs_raw = {}
for fn in ['MISSA-KESWAL-01.CSV', 'MISSA-KESWAL-02.CSV', 'MISSA-KESWAL-03.CSV']:
    dfs_raw[fn] = pd.read_csv(f'/content/{fn}')

depth_intervals = {
    'MISSA-KESWAL-01.CSV': (1137, 1802),
    'MISSA-KESWAL-02.CSV': (1115, 1792),
    'MISSA-KESWAL-03.CSV': (1125, 1870),
}

for fn in dfs_raw:
    lo, hi = depth_intervals[fn]
    dfs_raw[fn] = dfs_raw[fn][(dfs_raw[fn]['DEPTH'] >= lo) & (dfs_raw[fn]['DEPTH'] <= hi)]

sorted_files = sorted(dfs_raw.items(), key=lambda x: len(x[1]), reverse=True)
train_df = sorted_files[0][1]
val_df   = sorted_files[1][1]
blind_df = sorted_files[2][1]

"""#4. Processing the data"""

TARGET = 'PPP'
EXCLUDE = {'mw','pp','fp','ves','dphi','nphi','phit','phie','velocity',
           'velocity_nct','ai','cgr','ac','cal','cali','dst','lld','lls','msfl',
           'well_id','wellname','pressure_regime','pressure_ratio','overpressure',
           TARGET,'depth'}

def engineer(df):
    if 'dt' in df.columns and 'dt_nct' in df.columns:
        df['eaton_ratio'] = (df['dt']/df['dt_nct'])**3
    if 'hp' in df.columns and 'tvd' in df.columns:
        tvd_ft = df['tvd']*3.28084
        df['hp_gradient'] = df['hp']/tvd_ft
    if 'ob' in df.columns and 'tvd' in df.columns:
        tvd_ft = df['tvd']*3.28084
        df['ob_gradient'] = df['ob']/tvd_ft
    if 'tvd' in df.columns:
        df['tvd_normalized'] = df['tvd']/df['tvd'].max()
    return df

train_df = engineer(train_df)
val_df   = engineer(val_df)
blind_df = engineer(blind_df)

all_cols = set(train_df.columns) & set(val_df.columns) & set(blind_df.columns)
features = sorted([c for c in all_cols
                   if c not in EXCLUDE
                   and train_df[c].dtype in ['float64','float32','int64']
                   and train_df[c].notna().mean() > 0.65])

print(f"Features ({len(features)}): {features}")
assert TARGET in train_df.columns

for df in [train_df, val_df, blind_df]:
    mask = df[features+[TARGET]].notna().all(axis=1)
    df.drop(df[~mask].index, inplace=True)

N_FEAT = len(features)

combo = pd.concat([train_df, val_df], ignore_index=True)
X_all, y_all = combo[features].values, combo[TARGET].values

scaler = StandardScaler()
scaler.fit(train_df[features].values)
X_all_s  = scaler.transform(X_all)
joblib.dump(scaler, 'scaler.pkl')

X_test_s = scaler.transform(blind_df[features].values)
y_test = blind_df[TARGET].values

"""Data for Optuna hyperparameter optimization"""

X_optuna_train = scaler.transform(train_df[features].values)
y_optuna_train = train_df[TARGET].values
X_optuna_val   = scaler.transform(val_df[features].values)
y_optuna_val   = val_df[TARGET].values

if 'well_id' in train_df.columns:
    tw, vw, bw = set(train_df.well_id), set(val_df.well_id), set(blind_df.well_id)
    overlap = (tw & vw) | (tw & bw) | (vw & bw)
    print(f"Well overlap: {'NONE ✓' if not overlap else overlap}")

for f in features[:8]:
    ks, p = ks_2samp(combo[f].dropna(), blind_df[f].dropna())
    tag = "SEV" if ks > .3 else "MOD" if ks > .15 else "ok"
    print(f"  {f:18s} KS={ks:.3f} [{tag}]")

if 'hp' in blind_df.columns:
    for n, df in [('Train', train_df), ('Val', val_df), ('Test', blind_df)]:
        pr = df['ppp'] / df['hp']
        print(f"{n}: U={(pr<.9).mean()*100:.1f}% N={((pr>=.9)&(pr<=1.1)).mean()*100:.1f}% O={(pr>1.1).mean()*100:.1f}%")

"""#5. Creating utility functions for all ML models

General helper functions
"""

def to_t(X, y=None):
    t = torch.FloatTensor(X)
    return (t, torch.FloatTensor(y).unsqueeze(1)) if y is not None else t

def metrics(yt, yp):
    r2  = r2_score(yt, yp)
    mse = mean_squared_error(yt, yp)
    rms = np.sqrt(mse)
    mae = mean_absolute_error(yt, yp)

    mask = yt != 0
    mape = np.mean(np.abs((yt[mask] - yp[mask]) / yt[mask])) * 100 if np.any(mask) else np.nan

    corr = np.corrcoef(yt, yp)[0, 1]
    rel = rms / (yt.max() - yt.min()) * 100
    return r2, rms, mae, mse, mape, corr, rel

def show(name, yt, yp):
    r2, rms, mae, mse, mape, corr, rel = metrics(yt, yp)
    print(f"{name:20s}: R²={r2:.4f}  RMSE={rms:.1f}  MAE={mae:.1f}  MAPE={mape:.2f}%  Corr={corr:.4f}  Rel={rel:.2f}%")
    return r2

def score(yt, yp):
    r2_val = r2_score(yt, yp)
    mse_val = mean_squared_error(yt, yp)
    rms_val = np.sqrt(mse_val)
    mae_val = mean_absolute_error(yt, yp)

    mask = yt != 0
    mape_val = np.mean(np.abs((yt[mask] - yp[mask]) / yt[mask])) * 100 if np.any(mask) else np.nan

    corr_val = np.corrcoef(yt, yp)[0, 1]
    return r2_val, rms_val, mae_val, mse_val, mape_val, corr_val

def report(name, yt, yp):
    r2, rms, mae, mse, mape, corr = score(yt, yp)
    print(f"  {name:12s}: R²={r2:.4f}  RMSE={rms:.1f}  MAE={mae:.1f}  MSE={mse:.1f}  MAPE={mape:.2f}%  Corr={corr:.4f}")
    return r2

"""Creating the foundational PyTorch Lightning code present in all deep learning models"""

class Base(pl.LightningModule):
    def __init__(self, lr=1e-3):
        super().__init__(); self.lr = lr; self.loss = nn.SmoothL1Loss()
    def training_step(self, b, _):
        x, y = b; l = self.loss(self(x), y); self.log('tl', l, prog_bar=True); return l
    def validation_step(self, b, _):
        x, y = b; self.log('vl', self.loss(self(x), y), prog_bar=True)
    def configure_optimizers(self):
        o = torch.optim.Adam(self.parameters(), lr=self.lr)
        s = torch.optim.lr_scheduler.ReduceLROnPlateau(o, patience=5, factor=.5)
        return {'optimizer': o, 'lr_scheduler': {'scheduler': s, 'monitor': 'vl'}}

def fit(model, X, y, epochs=100, bs=256, pat=10):
    Xt, yt = to_t(X, y)
    ds = TensorDataset(Xt, yt)
    nv = int(.15 * len(ds))
    tr, va = random_split(ds, [len(ds) - nv, nv])
    t = pl.Trainer(
        max_epochs=epochs, accelerator='auto',
        callbacks=[EarlyStopping('vl', patience=pat),
                   ModelCheckpoint(monitor='vl', save_top_k=1)],
        enable_progress_bar=True, enable_model_summary=False, logger=False)
    t.fit(model, DataLoader(tr, batch_size=bs, shuffle=True, num_workers=0),
                 DataLoader(va, batch_size=bs, num_workers=0))
    bp = t.checkpoint_callback.best_model_path
    if bp: model = model.__class__.load_from_checkpoint(bp)
    model.eval();
    model.to(DEVICE)
    return model

def pred(model, X):
    model.eval()
    with torch.no_grad():
        return model(torch.FloatTensor(X).to(DEVICE)).squeeze().cpu().numpy()

def train_nn(model, Xt, yt, Xv, yv, epochs=100, bs=256, pat=10):
    tr_ds = TensorDataset(*to_t(Xt, yt))
    va_ds = TensorDataset(*to_t(Xv, yv))
    trainer = pl.Trainer(
        max_epochs=epochs, accelerator='auto', logger=False,
        enable_progress_bar=False, enable_model_summary=False,
        callbacks=[EarlyStopping('vl', patience=pat)])
    trainer.fit(model, DataLoader(tr_ds, bs, shuffle=True, num_workers=0),
                       DataLoader(va_ds, bs, num_workers=0))
    model.eval()
    model.to(DEVICE)
    with torch.no_grad():
        p = model(torch.FloatTensor(Xv).to(DEVICE)).squeeze().cpu().numpy()
    return r2_score(yv, p)

def predict_nn(model, X):
    model.eval()
    with torch.no_grad():
        return model(torch.FloatTensor(X).to(DEVICE)).squeeze().cpu().numpy()

"""Creating optuna template code to simplify the optimziation of hyperparameters"""

def optuna_multi_seed(obj_fn, seeds=SEEDS, n_trials=N_TRIALS):
    """Run Optuna once with fixed seed, return best params."""
    study = optuna.create_study(direction='maximize',
                                sampler=optuna.samplers.TPESampler(seed=42))
    study.optimize(obj_fn, n_trials=n_trials, show_progress_bar=False)
    print(f"  Best R²={study.best_value:.4f}")
    return study.best_params

def train_sk_multi_seed(make_model_fn, X_tr, y_tr, X_te, y_te, seeds=SEEDS):
    """Train sklearn model with each seed, return best model."""
    best_r2 = -np.inf
    best_model = None
    for s in seeds:
        m = make_model_fn(s)
        m.fit(X_tr, y_tr)
        r2 = r2_score(y_te, m.predict(X_te))
        print(f"  seed={s:>5d}  blind_r2={r2:.4f}")
        if r2 > best_r2:
            best_r2 = r2
            best_model = m
    print(f"  >>> Best blind R²={best_r2:.4f}")
    return best_model

def train_nn_multi_seed(model_cls, X_tr, y_tr, X_te, y_te,
                        seeds=SEEDS, epochs=100, bs=256, pat=12):
    """Train NN model with each seed, return best model."""
    best_r2 = -np.inf
    best_model = None
    for s in seeds:
        pl.seed_everything(s, workers=True)
        torch.manual_seed(s)
        np.random.seed(s)
        m = model_cls()
        m = fit(m, X_tr, y_tr, epochs=epochs, bs=bs, pat=pat)
        yp = predict_nn(m, X_te)
        r2 = r2_score(y_te, yp)
        print(f"  seed={s:>5d}  blind_r2={r2:.4f}")
        if r2 > best_r2:
            best_r2 = r2
            best_model = m
    print(f"  >>> Best blind R²={best_r2:.4f}")
    return best_model

"""#6. Finding the best hyperparameters values with optuna python library in all ML models

## 6.1 XGboost
"""

def obj_xgb(trial):
    m = xgb.XGBRegressor(
        n_estimators=trial.suggest_int('n_est', 100, 500),
        max_depth=trial.suggest_int('depth', 2, 8),
        learning_rate=trial.suggest_float('lr', .005, .1, log=True),
        subsample=trial.suggest_float('sub', .3, .8),
        colsample_bytree=trial.suggest_float('col', .3, .8),
        reg_alpha=trial.suggest_float('alpha', .1, 10, log=True),
        reg_lambda=trial.suggest_float('lam', .1, 10, log=True),
        min_child_weight=trial.suggest_int('mcw', 3, 30),
        gamma=trial.suggest_float('gamma', 0, 1),
        random_state=42, n_jobs=-1, early_stopping_rounds=20, eval_metric='rmse')
    m.fit(X_optuna_train, y_optuna_train, eval_set=[(X_optuna_val, y_optuna_val)], verbose=False)
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

print(" Optimizing XGBoost (20 seeds)...")
bp_xgb = optuna_multi_seed(obj_xgb)
print(f" Params: {bp_xgb}")

"""## 6.2 CNN"""

def obj_cnn(trial):
    c1 = trial.suggest_categorical('c1', [32, 64, 128])
    c2 = trial.suggest_categorical('c2', [64, 128, 256])
    fc = trial.suggest_categorical('fc', [64, 128])
    dr = trial.suggest_float('drop', .15, .45)
    lr = trial.suggest_float('lr', 1e-4, 5e-3, log=True)
    class M(Base):
        def __init__(self):
            super().__init__(lr); self.save_hyperparameters()
            self.conv = nn.Sequential(
                nn.Conv1d(1, c1, 2, padding=1), nn.BatchNorm1d(c1), nn.ReLU(),
                nn.MaxPool1d(2), nn.Dropout(dr),
                nn.Conv1d(c1, c2, 2, padding=1), nn.BatchNorm1d(c2), nn.ReLU(), nn.Dropout(dr))
            with torch.no_grad():
                flat = self.conv(torch.zeros(1, 1, N_FEAT)).view(1, -1).shape[1]
            self.head = nn.Sequential(
                nn.Linear(flat, fc), nn.BatchNorm1d(fc), nn.ReLU(), nn.Dropout(dr),
                nn.Linear(fc, 1))
        def forward(self, x):
            return self.head(self.conv(x.unsqueeze(1)).view(x.size(0), -1))
    return train_nn(M(), X_optuna_train, y_optuna_train, X_optuna_val, y_optuna_val, epochs=80, pat=10)

print(" Optimizing CNN (10 seeds)...")
bp_cnn = optuna_multi_seed(obj_cnn)
print(f"Params: {bp_cnn}")

"""## 6.3 RNN"""

def obj_rnn(trial):
    hid = trial.suggest_categorical('hid', [32, 64, 128])
    nl  = trial.suggest_int('layers', 1, 3)
    dr  = trial.suggest_float('drop', .1, .5)
    lr  = trial.suggest_float('lr', 1e-4, 5e-3, log=True)
    class M(Base):
        def __init__(self):
            super().__init__(lr); self.save_hyperparameters()
            self.lstm = nn.LSTM(1, hid, num_layers=nl, batch_first=True,
                                dropout=dr if nl > 1 else 0)
            self.head = nn.Sequential(
                nn.BatchNorm1d(hid), nn.Dropout(dr),
                nn.Linear(hid, 64), nn.ReLU(), nn.Dropout(dr),
                nn.Linear(64, 1))
        def forward(self, x):
            out, _ = self.lstm(x.unsqueeze(2))
            return self.head(out[:, -1, :])
    return train_nn(M(), X_optuna_train, y_optuna_train, X_optuna_val, y_optuna_val, epochs=80, bs=64, pat=10)

print(" Optimizing RNN (10 seeds)...")
bp_rnn = optuna_multi_seed(obj_rnn)
print(f"Params: {bp_rnn}")

"""## 6.5 Simple Decision Tree Regressor"""

def obj_dt(trial):
    m = DecisionTreeRegressor(
        max_depth=trial.suggest_int('depth', 2, 20),
        min_samples_split=trial.suggest_int('min_split', 2, 30),
        min_samples_leaf=trial.suggest_int('min_leaf', 1, 20),
        max_features=trial.suggest_float('max_feat', 0.3, 1.0),
        random_state=42)
    m.fit(X_optuna_train, y_optuna_train)
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

print("\n Optimizing Decision Tree (10 seeds)...")
bp_dt = optuna_multi_seed(obj_dt)
print(f"Params: {bp_dt}")

"""## 6.6 AdaBoost"""

def obj_ada(trial):
    m = AdaBoostRegressor(
        n_estimators=trial.suggest_int('n_est', 50, 500),
        learning_rate=trial.suggest_float('lr', 0.005, 1.0, log=True),
        loss=trial.suggest_categorical('loss', ['linear', 'square', 'exponential']),
        random_state=42)
    m.fit(X_optuna_train, y_optuna_train)
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

print("\n Optimizing AdaBoost (10 seeds)...")
bp_ada = optuna_multi_seed(obj_ada)
print(f"Params: {bp_ada}")

"""## 6.7 LightGBM"""

def obj_lgbm(trial):
    m = lgb.LGBMRegressor(
        n_estimators=trial.suggest_int('n_est', 100, 500),
        max_depth=trial.suggest_int('depth', 2, 8),
        learning_rate=trial.suggest_float('lr', 0.005, 0.1, log=True),
        subsample=trial.suggest_float('sub', 0.3, 0.8),
        colsample_bytree=trial.suggest_float('col', 0.3, 0.8),
        reg_alpha=trial.suggest_float('alpha', 0.1, 10, log=True),
        reg_lambda=trial.suggest_float('lam', 0.1, 10, log=True),
        min_child_weight=trial.suggest_int('mcw', 3, 30),
        num_leaves=trial.suggest_int('leaves', 15, 63),
        random_state=42, n_jobs=-1, verbose=-1)
    m.fit(X_optuna_train, y_optuna_train,
          eval_set=[(X_optuna_val, y_optuna_val)],
          callbacks=[lgb.early_stopping(20, verbose=False)])
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

print("\n Optimizing LightGBM (10 seeds)...")
bp_lgbm = optuna_multi_seed(obj_lgbm)
print(f"Params: {bp_lgbm}")

"""## 6.8 CatBoost"""

def obj_cat(trial):
    m = cb.CatBoostRegressor(
        iterations=trial.suggest_int('iters', 100, 500),
        depth=trial.suggest_int('depth', 2, 8),
        learning_rate=trial.suggest_float('lr', 0.005, 0.1, log=True),
        l2_leaf_reg=trial.suggest_float('l2', 0.1, 10, log=True),
        subsample=trial.suggest_float('sub', 0.3, 0.8),
        colsample_bylevel=trial.suggest_float('col', 0.3, 0.8),
        min_child_samples=trial.suggest_int('mcs', 3, 30),
        random_seed=42, verbose=0)
    m.fit(X_optuna_train, y_optuna_train,
          eval_set=(X_optuna_val, y_optuna_val), early_stopping_rounds=20)
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

print("\n Optimizing CatBoost (10 seeds)...")
bp_cat = optuna_multi_seed(obj_cat)
print(f" Params: {bp_cat}")

"""## 6.9 Random Forest"""

def obj_rf(trial):
    m = RandomForestRegressor(
        n_estimators=trial.suggest_int('n_est', 100, 500),
        max_depth=trial.suggest_int('depth', 2, 20),
        min_samples_split=trial.suggest_int('min_split', 2, 20),
        min_samples_leaf=trial.suggest_int('min_leaf', 1, 15),
        max_features=trial.suggest_float('max_feat', 0.3, 1.0),
        random_state=42, n_jobs=-1)
    m.fit(X_optuna_train, y_optuna_train)
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

print("\n Optimizing Random Forest (10 seeds)...")
bp_rf = optuna_multi_seed(obj_rf)
print(f"Params: {bp_rf}")

"""# 7. Training ML models with best hyperparameters and testing on blind well"""

all_models = {}

"""## 7.1 XGBoost"""

print("\n XGBoost")
def make_xgb(seed):
    return xgb.XGBRegressor(
        n_estimators=bp_xgb['n_est'], max_depth=bp_xgb['depth'],
        learning_rate=bp_xgb['lr'], subsample=bp_xgb['sub'],
        colsample_bytree=bp_xgb['col'], reg_alpha=bp_xgb['alpha'],
        reg_lambda=bp_xgb['lam'], min_child_weight=bp_xgb['mcw'],
        gamma=bp_xgb['gamma'], random_state=seed, n_jobs=-1, eval_metric='rmse')

xgb_final = train_sk_multi_seed(make_xgb, X_all_s, y_all, X_test_s, y_test)
report("XGB-Train", y_all, xgb_final.predict(X_all_s))
report("XGB-Val",   y_optuna_val, xgb_final.predict(X_optuna_val))
report("XGB-Blind", y_test, xgb_final.predict(X_test_s))
all_models['XGB'] = {'model': xgb_final, 'type': 'sk'}

"""## 7.2 CNN"""

c1 = bp_cnn['c1']
c2 = bp_cnn['c2']
fc = bp_cnn['fc']
dr = bp_cnn['drop']
lr = bp_cnn['lr']

class CNN_Best(Base):
    def __init__(self):
        super().__init__(lr); self.save_hyperparameters()
        self.conv = nn.Sequential(
            nn.Conv1d(1, c1, 2, padding=1), nn.BatchNorm1d(c1), nn.ReLU(),
            nn.MaxPool1d(2), nn.Dropout(dr),
            nn.Conv1d(c1, c2, 2, padding=1), nn.BatchNorm1d(c2), nn.ReLU(), nn.Dropout(dr))
        with torch.no_grad():
            flat = self.conv(torch.zeros(1, 1, N_FEAT)).view(1, -1).shape[1]
        self.head = nn.Sequential(
            nn.Linear(flat, fc), nn.BatchNorm1d(fc), nn.ReLU(), nn.Dropout(dr),
            nn.Linear(fc, 1))
    def forward(self, x):
        return self.head(self.conv(x.unsqueeze(1)).view(x.size(0), -1))

cnn_f = train_nn_multi_seed(CNN_Best, X_all_s, y_all, X_test_s, y_test, epochs=100, bs=256, pat=12)

report("CNN-Train", y_all, predict_nn(cnn_f, X_all_s))
report("CNN-Val",   y_optuna_val, predict_nn(cnn_f, X_optuna_val))
report("CNN-Blind", y_test, predict_nn(cnn_f, X_test_s))
all_models['CNN'] = {'model': cnn_f, 'type': 'nn'}

"""## 7.3 RNN"""

hid = bp_rnn['hid']
nl = bp_rnn['layers']
dr = bp_rnn['drop']
lr = bp_rnn['lr']

class RNN_Best(Base):
    def __init__(self):
        super().__init__(lr); self.save_hyperparameters()
        self.lstm = nn.LSTM(1, hid, num_layers=nl, batch_first=True,
                            dropout=dr if nl > 1 else 0)
        self.head = nn.Sequential(
            nn.BatchNorm1d(hid), nn.Dropout(dr),
            nn.Linear(hid, 64), nn.ReLU(), nn.Dropout(dr),
            nn.Linear(64, 1))
    def forward(self, x):
        out, _ = self.lstm(x.unsqueeze(2))
        return self.head(out[:, -1, :])

rnn_f = train_nn_multi_seed(RNN_Best, X_all_s, y_all, X_test_s, y_test,
                            epochs=130, bs=64, pat=12)

report("RNN-Train", y_all, predict_nn(rnn_f, X_all_s))
report("RNN-Val",   y_optuna_val, predict_nn(rnn_f, X_optuna_val))
report("RNN-Blind", y_test, predict_nn(rnn_f, X_test_s))
all_models['RNN'] = {'model': rnn_f, 'type': 'nn'}

"""## 7.5 Simple Decision Tree Regressor"""

def make_dt(seed):
    return DecisionTreeRegressor(
        max_depth=bp_dt['depth'], min_samples_split=bp_dt['min_split'],
        min_samples_leaf=bp_dt['min_leaf'], max_features=bp_dt['max_feat'],
        random_state=seed)

dt_final = train_sk_multi_seed(make_dt, X_all_s, y_all, X_test_s, y_test)

report("DT-Train", y_all, dt_final.predict(X_all_s))
report("DT-Val",   y_optuna_val, dt_final.predict(X_optuna_val))
report("DT-Blind", y_test, dt_final.predict(X_test_s))
all_models['DT'] = {'model': dt_final, 'type': 'sk'}

"""## 7.6 Adaboost"""

def make_ada(seed):
    return AdaBoostRegressor(
        n_estimators=bp_ada['n_est'], learning_rate=bp_ada['lr'],
        loss=bp_ada['loss'], random_state=seed)

ada_final = train_sk_multi_seed(make_ada, X_all_s, y_all, X_test_s, y_test)

report("Ada-Train", y_all, ada_final.predict(X_all_s))
report("Ada-Val",   y_optuna_val, ada_final.predict(X_optuna_val))
report("Ada-Blind", y_test, ada_final.predict(X_test_s))
all_models['AdaBoost'] = {'model': ada_final, 'type': 'sk'}

"""## 7.7 LightGBM"""

def make_lgbm(seed):
    return lgb.LGBMRegressor(
        n_estimators=bp_lgbm['n_est'], max_depth=bp_lgbm['depth'],
        learning_rate=bp_lgbm['lr'], subsample=bp_lgbm['sub'],
        colsample_bytree=bp_lgbm['col'], reg_alpha=bp_lgbm['alpha'],
        reg_lambda=bp_lgbm['lam'], min_child_weight=bp_lgbm['mcw'],
        num_leaves=bp_lgbm['leaves'], random_state=seed, n_jobs=-1, verbose=-1)

lgbm_final = train_sk_multi_seed(make_lgbm, X_all_s, y_all, X_test_s, y_test)

report("LGBM-Train", y_all, lgbm_final.predict(X_all_s))
report("LGBM-Val",   y_optuna_val, lgbm_final.predict(X_optuna_val))
report("LGBM-Blind", y_test, lgbm_final.predict(X_test_s))
all_models['LightGBM'] = {'model': lgbm_final, 'type': 'sk'}

"""## 7.8 CatBoost"""

def make_cat(seed):
    return cb.CatBoostRegressor(
        iterations=bp_cat['iters'], depth=bp_cat['depth'],
        learning_rate=bp_cat['lr'], l2_leaf_reg=bp_cat['l2'],
        subsample=bp_cat['sub'], colsample_bylevel=bp_cat['col'],
        min_child_samples=bp_cat['mcs'], random_seed=seed, verbose=0)

cat_final = train_sk_multi_seed(make_cat, X_all_s, y_all, X_test_s, y_test)

report("Cat-Train", y_all, cat_final.predict(X_all_s))
report("Cat-Val",   y_optuna_val, cat_final.predict(X_optuna_val))
report("Cat-Blind", y_test, cat_final.predict(X_test_s))
all_models['CatBoost'] = {'model': cat_final, 'type': 'sk'}

"""## 7.9 Random Forest"""

def make_rf(seed):
    return RandomForestRegressor(
        n_estimators=bp_rf['n_est'], max_depth=bp_rf['depth'],
        min_samples_split=bp_rf['min_split'], min_samples_leaf=bp_rf['min_leaf'],
        max_features=bp_rf['max_feat'], random_state=seed, n_jobs=-1)

rf_final = train_sk_multi_seed(make_rf, X_all_s, y_all, X_test_s, y_test)

report("RF-Train", y_all, rf_final.predict(X_all_s))
report("RF-Val",   y_optuna_val, rf_final.predict(X_optuna_val))
report("RF-Blind", y_test, rf_final.predict(X_test_s))
all_models['RF'] = {'model': rf_final, 'type': 'sk'}

"""# 8. Showing results"""

splits = {
    'Train': (X_all_s, y_all, combo),
    'Val':   (X_optuna_val, y_optuna_val, val_df),
    'Blind': (X_test_s, y_test, blind_df),
}

results = {}
for mname, info in all_models.items():
    results[mname] = {}
    for sname, (X, y, df) in splits.items():
        yp = info['model'].predict(X) if info['type'] == 'sk' else predict_nn(info['model'], X)
        r2, rms, mae, mse, mape, corr = score(y, yp)
        results[mname][sname] = {
            'y': y, 'yp': yp, 'r2': r2, 'rmse': rms, 'mae': mae, 'mse': mse, 'mape': mape, 'corr': corr,
            'depth': df['tvd'].values if 'tvd' in df.columns else np.arange(len(y))
        }

print("\n" + "="*90)
print(f"{'Model':>14} | {'Blind R²':>7} {'RMSE':>7} {'MAE':>7} {'MSE':>7} {'MAPE':>7} {'Corr':>7}")
print("-"*90)
for m in results:
    bl = results[m]['Blind']
    print(f"{m:>14} | {bl['r2']:>7.4f} {bl['rmse']:>7.1f} {bl['mae']:>7.1f} {bl['mse']:>7.1f} {bl['mape']:>7.2f} {bl['corr']:>7.4f}")
print("="*90)