# -*- coding: utf-8 -*-
"""optimal_five_good_baselines.ipynb

Automatically generated by Colab.

"""

"""# 1. Installing libraries

Installing latex to create images
"""

!apt-get -qq install -y fonts-freefont-ttf texlive-latex-extra texlive-fonts-recommended dvipng cm-super

"""Installing uv to install python packatges faster"""

!pip install uv

!uv pip install gdown torch pytorch_lightning xgboost optuna lightgbm catboost tqdm scienceplots

"""# 2. Importing libraries and taking configurations"""

import json
import os
import warnings
from collections import Counter

import numpy as np
import pandas as pd
from scipy.stats import ks_2samp

from sklearn.ensemble import AdaBoostRegressor, RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeRegressor
import catboost as cb
import lightgbm as lgb
import xgboost as xgb

import torch
import pytorch_lightning as pl

import optuna

import matplotlib
import matplotlib.pyplot as plt
import matplotlib.font_manager
import scienceplots
import seaborn as sns

import gdown
import joblib
from tqdm import tqdm

import json, numpy as np

from optuna.visualization.matplotlib import plot_optimization_history, plot_param_importances, plot_parallel_coordinate, plot_contour

matplotlib.font_manager._load_fontmanager(try_read_cache=False)

plt.style.use(['science'])

optuna.logging.set_verbosity(optuna.logging.WARNING)
warnings.filterwarnings('ignore')
np.random.seed(42); torch.manual_seed(42)
pl.seed_everything(42, workers=True)

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

SEEDS = [42, 137, 256, 1024, 7, 314, 999, 2048, 55, 8080, 12345, 67890, 101, 404, 808, 1337, 2023, 9999, 777, 31415]

print(f"PyTorch {torch.__version__} | PL {pl.__version__} | {DEVICE}")

all_seed_runs = {m: {} for m in ['XGB', 'LightGBM', 'CatBoost', 'AdaBoost', 'RF']}

N_TRIALS = 50

"""#3. Importing wells data"""

dfs_raw = {}
for fn in ['MISSA-KESWAL-01.CSV', 'MISSA-KESWAL-02.CSV', 'MISSA-KESWAL-03.CSV']:
    dfs_raw[fn] = pd.read_csv(f'/content/{fn}')


depth_intervals = {
    'MISSA-KESWAL-01.CSV': (1137, 1802),
    'MISSA-KESWAL-02.CSV': (1115, 1792),
    'MISSA-KESWAL-03.CSV': (1125, 1870),
}

for fn in dfs_raw:
    lo, hi = depth_intervals[fn]
    dfs_raw[fn] = dfs_raw[fn][(dfs_raw[fn]['DEPTH'] >= lo) & (dfs_raw[fn]['DEPTH'] <= hi)]

sorted_files = sorted(dfs_raw.items(), key=lambda x: len(x[1]), reverse=True)
train_df = sorted_files[0][1]
val_df   = sorted_files[1][1]
blind_df = sorted_files[2][1]

print(f"Train: {len(train_df):,} rows ({sorted_files[0][0]})")
print(f"Val:   {len(val_df):,} rows ({sorted_files[1][0]})")
print(f"Blind: {len(blind_df):,} rows ({sorted_files[2][0]})")

"""#4. Processing the data"""

TARGET = 'PPP'
EXCLUDE = {'mw','pp','fp','ves','dphi','nphi','phit','phie','velocity',
           'velocity_nct','ai','cgr','ac','cal','cali','dst','lld','lls','msfl',
           'well_id','wellname','pressure_regime','pressure_ratio','overpressure',
           TARGET,'depth'}

def engineer(df):
    if 'dt' in df.columns and 'dt_nct' in df.columns:
        df['eaton_ratio'] = (df['dt']/df['dt_nct'])**3
    if 'hp' in df.columns and 'tvd' in df.columns:
        tvd_ft = df['tvd']*3.28084
        df['hp_gradient'] = df['hp']/tvd_ft
    if 'ob' in df.columns and 'tvd' in df.columns:
        tvd_ft = df['tvd']*3.28084
        df['ob_gradient'] = df['ob']/tvd_ft
    if 'tvd' in df.columns:
        df['tvd_normalized'] = df['tvd']/df['tvd'].max()
    return df

train_df = engineer(train_df)
val_df   = engineer(val_df)
blind_df = engineer(blind_df)

all_cols = set(train_df.columns) & set(val_df.columns) & set(blind_df.columns)
features = sorted([c for c in all_cols
                   if c not in EXCLUDE
                   and train_df[c].dtype in ['float64','float32','int64']
                   and train_df[c].notna().mean() > 0.65])

print(f"Features ({len(features)}): {features}")
assert TARGET in train_df.columns

for df in [train_df, val_df, blind_df]:
    mask = df[features+[TARGET]].notna().all(axis=1)
    df.drop(df[~mask].index, inplace=True)

N_FEAT = len(features)

combo = pd.concat([train_df, val_df], ignore_index=True)
X_all, y_all = combo[features].values, combo[TARGET].values

scaler = StandardScaler()
scaler.fit(train_df[features].values)
X_all_s  = scaler.transform(X_all)
joblib.dump(scaler, 'scaler.pkl')

X_test_s = scaler.transform(blind_df[features].values)
y_test = blind_df[TARGET].values

"""Data for Optuna hyperparameter optimization"""

X_optuna_train = scaler.transform(train_df[features].values)
y_optuna_train = train_df[TARGET].values
X_optuna_val   = scaler.transform(val_df[features].values)
y_optuna_val   = val_df[TARGET].values

if 'well_id' in train_df.columns:
    tw, vw, bw = set(train_df.well_id), set(val_df.well_id), set(blind_df.well_id)
    overlap = (tw & vw) | (tw & bw) | (vw & bw)
    print(f"Well overlap: {'NONE ✓' if not overlap else overlap}")

for f in features[:8]:
    ks, p = ks_2samp(combo[f].dropna(), blind_df[f].dropna())
    tag = "SEV" if ks > .3 else "MOD" if ks > .15 else "ok"
    print(f"  {f:18s} KS={ks:.3f} [{tag}]")

if 'hp' in blind_df.columns:
    for n, df in [('Train', train_df), ('Val', val_df), ('Test', blind_df)]:
        pr = df['ppp'] / df['hp']
        print(f"{n}: U={(pr<.9).mean()*100:.1f}% N={((pr>=.9)&(pr<=1.1)).mean()*100:.1f}% O={(pr>1.1).mean()*100:.1f}%")

"""#5. Creating utility functions for all ML models"""

def score(yt, yp):
    r2_val = r2_score(yt, yp)
    mse_val = mean_squared_error(yt, yp)
    rms_val = np.sqrt(mse_val)
    mae_val = mean_absolute_error(yt, yp)

    mask = yt != 0
    mape_val = np.mean(np.abs((yt[mask] - yp[mask]) / yt[mask])) * 100 if np.any(mask) else np.nan

    corr_val = np.corrcoef(yt, yp)[0, 1]
    return r2_val, rms_val, mae_val, mse_val, mape_val, corr_val

def report(name, yt, yp):
    r2, rms, mae, mse, mape, corr = score(yt, yp)
    print(f"  {name:12s}: R²={r2:.4f}  RMSE={rms:.1f}  MAE={mae:.1f}  MSE={mse:.1f}  MAPE={mape:.2f}%  Corr={corr:.4f}")
    return r2

"""#6. Finding the best hyperparameters values with optuna python library in all ML models"""

studies = {}

"""## 6.1 XGboost"""

def obj_xgb(trial, seed = 42):
    m = xgb.XGBRegressor(
        n_estimators=trial.suggest_int('n_est', 100, 500),
        max_depth=trial.suggest_int('depth', 2, 8),
        learning_rate=trial.suggest_float('lr', .005, .1, log=True),
        subsample=trial.suggest_float('sub', .3, .8),
        colsample_bytree=trial.suggest_float('col', .3, .8),
        reg_alpha=trial.suggest_float('alpha', .1, 10, log=True),
        reg_lambda=trial.suggest_float('lam', .1, 10, log=True),
        min_child_weight=trial.suggest_int('mcw', 3, 30),
        gamma=trial.suggest_float('gamma', 0, 1),
        random_state=seed, n_jobs=-1, early_stopping_rounds=20, eval_metric='rmse')
    m.fit(X_optuna_train, y_optuna_train, eval_set=[(X_optuna_val, y_optuna_val)], verbose=False)
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

# Step 1: Tune once
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(lambda trial: obj_xgb(trial, 42), n_trials=N_TRIALS, show_progress_bar=True)
bp_xgb = study.best_params

# Step 2: Reuse same params for all seeds
for seed in SEEDS:
    all_seed_runs['XGB'][seed] = {'params': bp_xgb}

studies['XGB'] = study

"""## 6.2 AdaBoost"""

def obj_ada(trial, seed = 42):
    m = AdaBoostRegressor(
        n_estimators=trial.suggest_int('n_est', 50, 500),
        learning_rate=trial.suggest_float('lr', 0.005, 1.0, log=True),
        loss=trial.suggest_categorical('loss', ['linear', 'square', 'exponential']),
        random_state=seed)
    m.fit(X_optuna_train, y_optuna_train)
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

# Step 1: Tune once
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(lambda trial: obj_ada(trial, 42), n_trials=N_TRIALS, show_progress_bar=True)
bp_ada = study.best_params

# Step 2: Reuse same params for all seeds
for seed in SEEDS:
    all_seed_runs['AdaBoost'][seed] = {'params': bp_ada}

studies['AdaBoost'] = study

"""## 6.3 LightGBM"""

def obj_lgbm(trial, seed=42):
    m = lgb.LGBMRegressor(
        n_estimators=trial.suggest_int('n_est', 100, 500),
        max_depth=trial.suggest_int('depth', 2, 8),
        learning_rate=trial.suggest_float('lr', 0.005, 0.1, log=True),
        subsample=trial.suggest_float('sub', 0.3, 0.8),
        colsample_bytree=trial.suggest_float('col', 0.3, 0.8),
        reg_alpha=trial.suggest_float('alpha', 0.1, 10, log=True),
        reg_lambda=trial.suggest_float('lam', 0.1, 10, log=True),
        min_child_weight=trial.suggest_int('mcw', 3, 30),
        num_leaves=trial.suggest_int('leaves', 15, 63),
        random_state=seed, n_jobs=-1, verbose=-1)
    m.fit(X_optuna_train, y_optuna_train,
          eval_set=[(X_optuna_val, y_optuna_val)],
          callbacks=[lgb.early_stopping(20, verbose=False)])
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

# Step 1: Tune once
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(lambda trial: obj_lgbm(trial, 42), n_trials=N_TRIALS, show_progress_bar=True)
bp_lgbm = study.best_params

# Step 2: Reuse same params for all seeds
for seed in SEEDS:
    all_seed_runs['LightGBM'][seed] = {'params': bp_lgbm}

studies['LightGBM'] = study

"""## 6.4 CatBoost"""

def obj_cat(trial, seed=42):
    m = cb.CatBoostRegressor(
        iterations=trial.suggest_int('iters', 100, 500),
        depth=trial.suggest_int('depth', 2, 8),
        learning_rate=trial.suggest_float('lr', 0.005, 0.1, log=True),
        l2_leaf_reg=trial.suggest_float('l2', 0.1, 10, log=True),
        subsample=trial.suggest_float('sub', 0.3, 0.8),
        colsample_bylevel=trial.suggest_float('col', 0.3, 0.8),
        min_child_samples=trial.suggest_int('mcs', 3, 30),
        random_seed=seed, verbose=0)
    m.fit(X_optuna_train, y_optuna_train,
          eval_set=(X_optuna_val, y_optuna_val), early_stopping_rounds=20)
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

# Step 1: Tune once
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(lambda trial: obj_cat(trial, 42), n_trials=N_TRIALS, show_progress_bar=True)
bp_cat = study.best_params

# Step 2: Reuse same params for all seeds
for seed in SEEDS:
    all_seed_runs['CatBoost'][seed] = {'params': bp_cat}

studies['CatBoost'] = study

"""## 6.5 Random Forest"""

def obj_rf(trial, seed=42):
    m = RandomForestRegressor(
        n_estimators=trial.suggest_int('n_est', 100, 500),
        max_depth=trial.suggest_int('depth', 2, 20),
        min_samples_split=trial.suggest_int('min_split', 2, 20),
        min_samples_leaf=trial.suggest_int('min_leaf', 1, 15),
        max_features=trial.suggest_float('max_feat', 0.3, 1.0),
        random_state=seed, n_jobs=-1)
    m.fit(X_optuna_train, y_optuna_train)
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

# Step 1: Tune once
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(lambda trial: obj_rf(trial, 42), n_trials=N_TRIALS, show_progress_bar=True)
bp_rf = study.best_params

# Step 2: Reuse same params for all seeds
for seed in SEEDS:
    all_seed_runs['RF'][seed] = {'params': bp_rf}

studies['RF'] = study

"""## 6.6 Decision tree regressor"""

def obj_dt(trial, seed=42):
    m = DecisionTreeRegressor(
        max_depth=trial.suggest_int('depth', 2, 20),
        min_samples_split=trial.suggest_int('min_split', 2, 30),
        min_samples_leaf=trial.suggest_int('min_leaf', 1, 20),
        max_features=trial.suggest_float('max_feat', 0.3, 1.0),
        random_state=seed)
    m.fit(X_optuna_train, y_optuna_train)
    return r2_score(y_optuna_val, m.predict(X_optuna_val))

# Step 1: Tune once
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(lambda trial: obj_dt(trial, 42), n_trials=N_TRIALS, show_progress_bar=True)
bp_dt = study.best_params

# Step 2: Reuse same params for all seeds
all_seed_runs['DecisionTree'] = {}
for seed in SEEDS:
    all_seed_runs['DecisionTree'][seed] = {'params': bp_dt}

studies['DecisionTree'] = study

"""# 7. Running the tree models with the best parameters

## 7.1 Training XGBoost with the best hyperparameters
"""

for seed in tqdm(SEEDS, desc="XGB Training"):
    p = all_seed_runs['XGB'][seed]['params']
    m = xgb.XGBRegressor(
        n_estimators=p['n_est'], max_depth=p['depth'], learning_rate=p['lr'],
        subsample=p['sub'], colsample_bytree=p['col'], reg_alpha=p['alpha'],
        reg_lambda=p['lam'], min_child_weight=p['mcw'], gamma=p['gamma'],
        random_state=seed, n_jobs=-1, eval_metric='rmse')
    m.fit(X_all_s, y_all)
    all_seed_runs['XGB'][seed]['metrics'] = {
        'Train': score(y_all, m.predict(X_all_s)),
        'Val':   score(y_optuna_val, m.predict(X_optuna_val)),
        'Blind': score(y_test, m.predict(X_test_s)),
    }
    print(f"    Seed {seed:>5}: Train R²={all_seed_runs['XGB'][seed]['metrics']['Train'][0]:.4f}  "
          f"Val R²={all_seed_runs['XGB'][seed]['metrics']['Val'][0]:.4f}  "
          f"Blind R²={all_seed_runs['XGB'][seed]['metrics']['Blind'][0]:.4f}")

"""## 7.2 Training LGMboost with the best hyperparameters"""

for seed in tqdm(SEEDS, desc="LGBM Training"):
    p = all_seed_runs['LightGBM'][seed]['params']
    m = lgb.LGBMRegressor(
        n_estimators=p['n_est'], max_depth=p['depth'], learning_rate=p['lr'],
        subsample=p['sub'], colsample_bytree=p['col'], reg_alpha=p['alpha'],
        reg_lambda=p['lam'], min_child_weight=p['mcw'], num_leaves=p['leaves'],
        random_state=seed, n_jobs=-1, verbose=-1)
    m.fit(X_all_s, y_all)
    all_seed_runs['LightGBM'][seed]['metrics'] = {
        'Train': score(y_all, m.predict(X_all_s)),
        'Val':   score(y_optuna_val, m.predict(X_optuna_val)),
        'Blind': score(y_test, m.predict(X_test_s)),
    }
    print(f"    Seed {seed:>5}: Train R²={all_seed_runs['LightGBM'][seed]['metrics']['Train'][0]:.4f}  "
          f"Val R²={all_seed_runs['LightGBM'][seed]['metrics']['Val'][0]:.4f}  "
          f"Blind R²={all_seed_runs['LightGBM'][seed]['metrics']['Blind'][0]:.4f}")

"""## 7.3 Training catboost with the best hyperparameters"""

for seed in tqdm(SEEDS, desc="CatBoost Training"):
    p = all_seed_runs['CatBoost'][seed]['params']
    m = cb.CatBoostRegressor(
        iterations=p['iters'], depth=p['depth'], learning_rate=p['lr'],
        l2_leaf_reg=p['l2'], subsample=p['sub'], colsample_bylevel=p['col'],
        min_child_samples=p['mcs'], random_seed=seed, verbose=0)
    m.fit(X_all_s, y_all)
    all_seed_runs['CatBoost'][seed]['metrics'] = {
        'Train': score(y_all, m.predict(X_all_s)),
        'Val':   score(y_optuna_val, m.predict(X_optuna_val)),
        'Blind': score(y_test, m.predict(X_test_s)),
    }
    print(f"    Seed {seed:>5}: Train R²={all_seed_runs['CatBoost'][seed]['metrics']['Train'][0]:.4f}  "
          f"Val R²={all_seed_runs['CatBoost'][seed]['metrics']['Val'][0]:.4f}  "
          f"Blind R²={all_seed_runs['CatBoost'][seed]['metrics']['Blind'][0]:.4f}")

"""## 7.4 Training Adaboost with the best hyperparameters"""

for seed in tqdm(SEEDS, desc="AdaBoost Training"):
    p = all_seed_runs['AdaBoost'][seed]['params']
    m = AdaBoostRegressor(
        n_estimators=p['n_est'], learning_rate=p['lr'],
        loss=p['loss'], random_state=seed)
    m.fit(X_all_s, y_all)
    all_seed_runs['AdaBoost'][seed]['metrics'] = {
        'Train': score(y_all, m.predict(X_all_s)),
        'Val':   score(y_optuna_val, m.predict(X_optuna_val)),
        'Blind': score(y_test, m.predict(X_test_s)),
    }
    print(f"    Seed {seed:>5}: Train R²={all_seed_runs['AdaBoost'][seed]['metrics']['Train'][0]:.4f}  "
          f"Val R²={all_seed_runs['AdaBoost'][seed]['metrics']['Val'][0]:.4f}  "
          f"Blind R²={all_seed_runs['AdaBoost'][seed]['metrics']['Blind'][0]:.4f}")

"""## 7.5 Training Random Forest with the best hyperparameters"""

for seed in tqdm(SEEDS, desc="RF Training"):
    p = all_seed_runs['RF'][seed]['params']
    m = RandomForestRegressor(
        n_estimators=p['n_est'], max_depth=p['depth'],
        min_samples_split=p['min_split'], min_samples_leaf=p['min_leaf'],
        max_features=p['max_feat'], random_state=seed, n_jobs=-1)
    m.fit(X_all_s, y_all)
    all_seed_runs['RF'][seed]['metrics'] = {
        'Train': score(y_all, m.predict(X_all_s)),
        'Val':   score(y_optuna_val, m.predict(X_optuna_val)),
        'Blind': score(y_test, m.predict(X_test_s)),
    }
    print(f"    Seed {seed:>5}: Train R²={all_seed_runs['RF'][seed]['metrics']['Train'][0]:.4f}  "
          f"Val R²={all_seed_runs['RF'][seed]['metrics']['Val'][0]:.4f}  "
          f"Blind R²={all_seed_runs['RF'][seed]['metrics']['Blind'][0]:.4f}")

"""## 7.6 Decision tree regressor"""

for seed in tqdm(SEEDS, desc='DecisionTree Training'):
    p = all_seed_runs['DecisionTree'][seed]['params']
    m = DecisionTreeRegressor(
        max_depth=p['depth'],
        min_samples_split=p['min_split'],
        min_samples_leaf=p['min_leaf'],
        max_features=p['max_feat'],
        random_state=seed)
    m.fit(X_all_s, y_all)
    all_seed_runs['DecisionTree'][seed]['metrics'] = {
        'Train': score(y_all, m.predict(X_all_s)),
        'Val':   score(y_optuna_val, m.predict(X_optuna_val)),
        'Blind': score(y_test, m.predict(X_test_s)),
    }
    print(f"    Seed {seed:>5}: Train R²={all_seed_runs['DecisionTree'][seed]['metrics']['Train'][0]:.4f}  " +
          f"Val R²={all_seed_runs['DecisionTree'][seed]['metrics']['Val'][0]:.4f}  " +
          f"Blind R²={all_seed_runs['DecisionTree'][seed]['metrics']['Blind'][0]:.4f}")

"""## 7.7 Downloading all models and best performances"""

summary = {}
for name, seeds_data in all_seed_runs.items():
    best_seed = max(SEEDS, key=lambda s: seeds_data[s]['metrics']['Blind'][0])
    m = seeds_data[best_seed]['metrics']
    summary[name] = {
        'best_seed': best_seed,
        'params': seeds_data[best_seed]['params'],
        'metrics': {
            split: dict(zip(['r2','rmse','mae','mse','mape','corr'], [round(v,4) for v in vals]))
            for split, vals in m.items()
        },
        'blind_mean': {
            k: round(v, 4) for k, v in zip(
                ['r2','rmse','mae','mse','mape','corr'],
                np.array([seeds_data[s]['metrics']['Blind'] for s in SEEDS]).mean(0)
            )
        }
    }

with open('best_models_summary.json', 'w') as f:
    json.dump(summary, f, indent=2)

print(json.dumps(summary, indent=2))

os.makedirs('best_models', exist_ok=True)

best_builders = {
    'XGB':      lambda p, s: xgb.XGBRegressor(n_estimators=p['n_est'], max_depth=p['depth'], learning_rate=p['lr'],
                    subsample=p['sub'], colsample_bytree=p['col'], reg_alpha=p['alpha'], reg_lambda=p['lam'],
                    min_child_weight=p['mcw'], gamma=p['gamma'], random_state=s, n_jobs=-1, eval_metric='rmse'),
    'LightGBM': lambda p, s: lgb.LGBMRegressor(n_estimators=p['n_est'], max_depth=p['depth'], learning_rate=p['lr'],
                    subsample=p['sub'], colsample_bytree=p['col'], reg_alpha=p['alpha'], reg_lambda=p['lam'],
                    min_child_weight=p['mcw'], num_leaves=p['leaves'], random_state=s, n_jobs=-1, verbose=-1),
    'CatBoost': lambda p, s: cb.CatBoostRegressor(iterations=p['iters'], depth=p['depth'], learning_rate=p['lr'],
                    l2_leaf_reg=p['l2'], subsample=p['sub'], colsample_bylevel=p['col'],
                    min_child_samples=p['mcs'], random_seed=s, verbose=0),
    'AdaBoost': lambda p, s: AdaBoostRegressor(n_estimators=p['n_est'], learning_rate=p['lr'], loss=p['loss'], random_state=s),
    'RF':       lambda p, s: RandomForestRegressor(n_estimators=p['n_est'], max_depth=p['depth'],
                    min_samples_split=p['min_split'], min_samples_leaf=p['min_leaf'],
                    max_features=p['max_feat'], random_state=s, n_jobs=-1),
    'DecisionTree': lambda p, s: DecisionTreeRegressor(max_depth=p['depth'],
                    min_samples_split=p['min_split'], min_samples_leaf=p['min_leaf'],
                    max_features=p['max_feat'], random_state=s)
}

for name in all_seed_runs:
    best_seed = max(SEEDS, key=lambda s: all_seed_runs[name][s]['metrics']['Blind'][0])
    best_params = all_seed_runs[name][best_seed]['params']
    best_r2 = all_seed_runs[name][best_seed]['metrics']['Blind'][0]

    # Retrain and save
    m = best_builders[name](best_params, best_seed)
    m.fit(X_all_s, y_all)
    joblib.dump(m, f'best_models/{name}_best.pkl')
    json.dump({'seed': best_seed, 'params': best_params, 'blind_r2': best_r2},
              open(f'best_models/{name}_best_params.json', 'w'), indent=2)
    print(f"  {name:>10}: saved (seed={best_seed}, Blind R²={best_r2:.4f})")

print("\nAll best models saved to best_models/")

"""# 8. Seeing metrics

## 8.1 Print all hyperparameters and all runs according to all seeds
"""

METRIC_NAMES = ['r2', 'rmse', 'mae', 'mse', 'mape', 'corr']

for model_name in all_seed_runs:
    print(f"\n{'─'*130}")
    print(f" {model_name}")
    print(f"{'─'*130}")
    print(f"  {'Seed':>6} | {'Train R²':>8} {'RMSE':>8} {'MAE':>8} {'MAPE':>8} | "
          f"{'Val R²':>8} {'RMSE':>8} {'MAE':>8} {'MAPE':>8} | "
          f"{'Blind R²':>8} {'RMSE':>8} {'MAE':>8} {'MAPE':>8}")

    for seed in SEEDS:
        run = all_seed_runs[model_name][seed]
        tr = run['metrics']['Train']   # tuple: (r2, rmse, mae, mse, mape, corr)
        va = run['metrics']['Val']
        bl = run['metrics']['Blind']
        print(f"  {seed:>6} | {tr[0]:>8.4f} {tr[1]:>8.1f} {tr[2]:>8.1f} {tr[4]:>8.2f} | "
              f"{va[0]:>8.4f} {va[1]:>8.1f} {va[2]:>8.1f} {va[4]:>8.2f} | "
              f"{bl[0]:>8.4f} {bl[1]:>8.1f} {bl[2]:>8.1f} {bl[4]:>8.2f}")

    print(f"\n  Hyperparameters per seed:")
    for seed in SEEDS:
        p = all_seed_runs[model_name][seed]['params']
        p_str = ', '.join(f"{k}={v}" for k, v in p.items())
        print(f"    Seed {seed:>5}: {p_str}")

"""## 8.2 Averaging metrics"""

print(f"  {'Model':>12} | {'R²':>13} | {'RMSE':>13} | {'MAE':>13} | {'MAPE':>13} | {'Corr':>13}")
for m in all_seed_runs:
    v = np.array([all_seed_runs[m][s]['metrics']['Blind'] for s in SEEDS])
    mu, sd = v.mean(0), v.std(0)
    print(f"  {m:>12} | {mu[0]:.4f}±{sd[0]:.4f} | {mu[1]:.2f}±{sd[1]:.2f} | {mu[2]:.2f}±{sd[2]:.2f} | {mu[4]:.3f}±{sd[4]:.3f} | {mu[5]:.4f}±{sd[5]:.4f}")

"""## 8.3 Average across all hyperparameters"""

for model_name in all_seed_runs:
    print(f"\n  {model_name}:")
    param_keys = list(all_seed_runs[model_name][SEEDS[0]]['params'].keys())

    for pk in param_keys:
        values = [all_seed_runs[model_name][s]['params'][pk] for s in SEEDS]
        if isinstance(values[0], str):
            counts = Counter(values)
            dist_str = ', '.join(f"{v}: {c}/{len(SEEDS)}" for v, c in counts.most_common())
            print(f"    {pk:>15}: [categorical] {dist_str}")
        elif isinstance(values[0], int):
            arr = np.array(values, dtype=float)
            print(f"    {pk:>15}: mean={int(round(arr.mean()))}  std={int(round(arr.std()))}  min={int(arr.min())}  max={int(arr.max())}")
        else:
            arr = np.array(values, dtype=float)
            print(f"    {pk:>15}: mean={arr.mean()}  std={arr.std()}  min={arr.min()}  max={arr.max()}")

"""## 8.4 Ranking the models by R2 in blind well"""

ranking = []
for model_name in all_seed_runs:
    blind_r2s = [all_seed_runs[model_name][s]['metrics']['Blind'][0] for s in SEEDS]
    ranking.append((model_name, np.mean(blind_r2s), np.std(blind_r2s)))

ranking.sort(key=lambda x: x[1], reverse=True)
for rank, (mname, mean_r2, std_r2) in enumerate(ranking, 1):
    print(f"  #{rank} {mname:>12}: Blind R² = {mean_r2:.4f} ± {std_r2:.4f}")

"""## 8.5 Print graphs of metrics"""

SINGLE_COL   = 3.5
ONE_HALF_COL = 5.5
FULL_PAGE    = 7.5

plt.rcParams.update({
    'figure.figsize':      (SINGLE_COL, 2.8),
    'figure.dpi':          150,
    'savefig.dpi':         600,
    'font.family':         'serif',
    'font.serif':          ['Times', 'Times New Roman'],
    'font.size':           8,
    'axes.labelsize':      9,
    'xtick.labelsize':     7,
    'ytick.labelsize':     7,
    'legend.fontsize':     7,
    'axes.linewidth':      0.6,
    'lines.linewidth':     1.0,
    'grid.linewidth':      0.4,
    'xtick.major.width':   0.5,
    'ytick.major.width':   0.5,
    'xtick.minor.width':   0.3,
    'ytick.minor.width':   0.3,
    'xtick.direction':     'in',
    'ytick.direction':     'in',
    'xtick.minor.visible': True,
    'ytick.minor.visible': True,
    'xtick.top':           True,
    'ytick.right':         True,
    'legend.frameon':      False,
    'savefig.bbox':        'tight',
    'savefig.pad_inches':  0.02,
    'savefig.transparent': False,
})

# Colorblind-friendly palette (Paul Tol bright)
CB = ['#0077BB','#CC3311','#009988','#EE7733','#33BBEE','#EE3377','#BBBBBB']

"""Identify best model, retrain, predict"""

best_name = max(all_seed_runs,
                key=lambda m: np.mean([all_seed_runs[m][s]['metrics']['Blind'][0] for s in SEEDS]))
best_seed = max(SEEDS,
                key=lambda s: all_seed_runs[best_name][s]['metrics']['Blind'][0])
bp = all_seed_runs[best_name][best_seed]['params']

best_model = best_builders[best_name](bp, best_seed)
best_model.fit(X_all_s, y_all)
y_pred  = best_model.predict(X_test_s)
r2_bl   = r2_score(y_test, y_pred)
rmse_bl = np.sqrt(mean_squared_error(y_test, y_pred))
mae_bl  = mean_absolute_error(y_test, y_pred)
print(f"Best model: {best_name}  seed={best_seed}  Blind R2={r2_bl:.4f}  RMSE={rmse_bl:.1f}")

dcol  = next((c for c in ['DEPTH','depth','tvd'] if c in blind_df.columns), None)
depth = blind_df[dcol].values if dcol else np.arange(len(y_test))

"""Figure 5 — Blind-Well Composite Log"""

track_spec = [
    ('Gamma Ray',       ['gr','GR'],                                   'API'),
    ('Volume of Shale', ['vsh','VSH'],                                 r'$V_{sh}$ (v/v)'),
    ('Sonic \& NCT',    [('dt','DT'),('dt_nct','NCT')],               r'$\Delta t$ ($\mu$s/ft)'),
    ('Resistivity',     ['res_deep','RES_DEEP','rt','ild'],            r'Res ($\Omega\cdot$m)'),
]

fig, axes = plt.subplots(1, 5, figsize=(FULL_PAGE, 4.8), sharey=True)

for i, (title, cands, unit) in enumerate(track_spec):
    ax = axes[i]
    if i == 2:                                    # dual-curve track
        lstyles = ['-','--']
        for j, (cname, lbl) in enumerate(cands):
            if cname in blind_df.columns:
                ax.plot(blind_df[cname].values, depth,
                        color=CB[j], ls=lstyles[j], lw=0.8, label=lbl)
    else:
        for c in cands:
            if c in blind_df.columns:
                ax.plot(blind_df[c].values, depth,
                        color=CB[i], lw=0.8, label=c.upper())
                break
    ax.set_title(title, fontsize=8, pad=4)
    ax.set_xlabel(unit)
    ax.legend(loc='lower left')
    ax.invert_yaxis()
    ax.grid(True, alpha=0.25)

ax5 = axes[4]
pres_curves = [('hp','HP',CB[4],'-'), ('ob','OB',CB[6],'--'), ('ppp','PP (Eaton)',CB[1],'-.')]
for c, lbl, col, ls in pres_curves:
    if c in blind_df.columns:
        ax5.plot(blind_df[c].values, depth, color=col, ls=ls, lw=0.8, label=lbl)
ax5.plot(y_pred, depth, color=CB[5], ls='-', lw=1.0, label=f'{best_name} Pred.')
ax5.set_title('Pressure Profiles', fontsize=8, pad=4)
ax5.set_xlabel('Pressure (psi)')
ax5.legend(loc='lower left')
ax5.invert_yaxis()
ax5.grid(True, alpha=0.25)
axes[0].set_ylabel('Depth (m)')

fig.savefig('fig5_welllog_blind.pdf')
fig.savefig('fig5_welllog_blind.tiff', dpi=600)
plt.show()

"""Actual vs Predicted Scatter (single column)"""

fig, ax = plt.subplots(figsize=(SINGLE_COL, SINGLE_COL))
ax.scatter(y_test, y_pred, s=4, alpha=0.35, color=CB[0],
           edgecolors='none', rasterized=True, zorder=2)
lims = [min(y_test.min(), y_pred.min())*0.95,
        max(y_test.max(), y_pred.max())*1.05]
ax.plot(lims, lims, color=CB[1], ls='--', lw=0.8, label='1:1 line', zorder=3)
ax.set(xlim=lims, ylim=lims, aspect='equal',
       xlabel='Actual pore pressure (psi)',
       ylabel='Predicted pore pressure (psi)')
ax.text(0.05, 0.92, f'$R^2$ = {r2_bl:.4f}\nRMSE = {rmse_bl:.1f} psi\nMAE = {mae_bl:.1f} psi',
        transform=ax.transAxes, fontsize=7, verticalalignment='top',
        bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='#CCCCCC', alpha=0.9))
ax.legend(loc='lower right')
ax.grid(True, alpha=0.25)

fig.savefig('fig6_scatter.pdf')
fig.savefig('fig6_scatter.tiff', dpi=600)
plt.show()

"""Residual Analysis (1.5-column)"""

res  = y_test - y_pred
rho  = np.corrcoef(y_pred, res)[0, 1]
sig  = res.std()
sidx = np.argsort(y_pred)
win  = max(len(res) // 50, 10)
ma   = pd.Series(res[sidx]).rolling(win, center=True).mean()

fig, ax = plt.subplots(figsize=(ONE_HALF_COL, 3.0))
ax.scatter(y_pred, res, s=4, alpha=0.3, color=CB[3],
           edgecolors='none', rasterized=True, zorder=2)
ax.axhline(0, color='k', lw=0.6, zorder=1)
ax.plot(y_pred[sidx], ma.values, color=CB[2], ls='-', lw=1.2,
        label='Moving average', zorder=3)
ax.axhline( sig, color=CB[1], ls='--', lw=0.7, label=rf'$\pm\sigma$ = {sig:.1f} psi')
ax.axhline(-sig, color=CB[1], ls='--', lw=0.7)
ax.set(xlabel='Predicted pore pressure (psi)', ylabel='Residual (psi)')
ax.text(0.97, 0.95, rf'$\rho$ = {rho:.3f}',
        transform=ax.transAxes, fontsize=7, ha='right', va='top',
        bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='#CCCCCC', alpha=0.9))
ax.legend(loc='lower left')
ax.grid(True, alpha=0.25)

fig.savefig('fig7_residuals.pdf')
fig.savefig('fig7_residuals.tiff', dpi=600)
plt.show()

"""R² by Depth Interval"""

if dcol:
    dmin, dmax = depth.min(), depth.max()
    thirds  = np.linspace(dmin, dmax, 4)
    labels_d, centers, r2s = [], [], []
    tags = ['Shallow','Medium','Deep']
    for j in range(3):
        mask = (depth >= thirds[j]) & (depth < thirds[j+1] + (1 if j==2 else 0))
        if mask.sum() > 10:
            r2s.append(r2_score(y_test[mask], y_pred[mask]))
            centers.append((thirds[j]+thirds[j+1])/2)
            labels_d.append(f'{tags[j]}\n({thirds[j]:.0f}\u2013{thirds[j+1]:.0f} m)')

    fig, ax = plt.subplots(figsize=(SINGLE_COL, 2.8))
    ax.plot(centers, r2s, 'o-', color=CB[0], lw=1.2, ms=7,
            markerfacecolor='white', markeredgewidth=1.2, markeredgecolor=CB[0])
    for c, r in zip(centers, r2s):
        ax.annotate(f'{r:.3f}', (c, r), textcoords='offset points',
                    xytext=(0, 10), ha='center', fontsize=7, fontweight='bold')
    ax.set_xticks(centers)
    ax.set_xticklabels(labels_d)
    ax.set(ylabel=r'$R^2$', ylim=(0, 1.1))
    ax.grid(True, alpha=0.25)

    fig.savefig('fig8_depth_perf.pdf')
    fig.savefig('fig8_depth_perf.tiff', dpi=600)
    plt.show()

"""Optuna Visualizations for Best Model"""

obj_map = {'XGB': obj_xgb, 'LightGBM': obj_lgbm, 'CatBoost': obj_cat,
           'AdaBoost': obj_ada, 'RF': obj_rf, 'DecisionTree': obj_dt}

if best_name in obj_map:
    print(f"\nRunning Optuna ({best_name}, {N_TRIALS} trials) for plots...")
    viz_study = optuna.create_study(direction='maximize',
                                    sampler=optuna.samplers.TPESampler(seed=42))
    viz_study.optimize(lambda t: obj_map[best_name](t, 42),
                       n_trials=N_TRIALS, show_progress_bar=True)

    optuna_figs = [
        (plot_optimization_history, 'optuna_history',    'Optimization history',   (ONE_HALF_COL, 2.8)),
        (plot_param_importances,    'optuna_importance',  'Parameter importance',   (SINGLE_COL, 2.8)),
        (plot_parallel_coordinate,  'optuna_parallel',    'Parallel coordinate',    (FULL_PAGE, 3.0)),
        (plot_contour,              'optuna_contour',     'Parameter contour',      (ONE_HALF_COL, 4.0)),
    ]
    for plot_fn, fname, title, fsize in optuna_figs:
        try:
            fig = plt.figure(figsize=fsize)
            ax = plot_fn(viz_study)
            # Optuna returns Axes; resize current figure
            gcf = plt.gcf()
            gcf.set_size_inches(fsize)
            gcf.savefig(f'{fname}.pdf')
            gcf.savefig(f'{fname}.tiff', dpi=600)
            plt.show()
        except Exception as e:
            print(f"  Skipped {fname}: {e}")